### ISSUE TITLE
Bad JSON results in the response code 500

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1064]
Pushing bad JSON as part of the search documents results in `500` response code, although it should be reported as `400`. This case that goes to the document search is actually fixed in the `v1.0.28`, however, I guess we have more places in the code where this is still handled old way.

We should check if it's possible to have Jersey handle those directly by having `JsonNode` as the parameter value. Then we would not need to parse the JSON ourselves. If not then we should correctly handle cases where the JSON that comes to the users is bad (`where`, `fields`, raw payloads).

```
ERROR [jersey-server-managed-async-executor-6] 2021-06-25 12:32:34,874 DocumentResourceV2.java:923 - Error when executing request
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting a colon to separate field name and value
 at [Source: (String)"{"firstname" { $eq: "Donald}}"; line: 1, column: 15]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon2(ReaderBasedJsonParser.java:2226)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon(ReaderBasedJsonParser.java:2205)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:935)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4270)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2720)
        at io.stargate.web.docsapi.resources.DocumentResourceV2.lambda$searchDoc$8(DocumentResourceV2.java:860)
        at io.stargate.web.docsapi.resources.DocumentResourceV2.handle(DocumentResourceV2.java:905)
        at io.stargate.web.docsapi.resources.DocumentResourceV2.searchDoc(DocumentResourceV2.java:845)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.lambda$apply$0(ResourceMethodInvoker.java:387)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2$1.run(ServerRuntime.java:816)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2.run(ServerRuntime.java:811)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
INFO  [jersey-server-managed-async-executor-6] 2021-06-25 12:32:34,876 Slf4jRequestLogWriter.java:62 - 10.0.67.163 - - [25/Jun/2021:12:32:34 +0000] "GET /v2/namespaces/workshop/collections/customers HTTP/1.0" 500 217 "-" "HTTPie/2.4.0" 3
```

**Comment by ivansenic** [comment]
Fixed by #1079.
