### ISSUE TITLE
Catch JsonParseException and return 400

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1110]
Noticed this error specifically with updateRows but there's other places it can happen. 

```java
ERROR [dw-484 - PUT /v2/keyspaces/ks1/tbl1/af2603d2-8c03-11eb-a03f-0ada685e000b] 2021-07-15 12:11:04,885 RequestHandler.java:96 - Error when executing request
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'foo': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"{
    "description": "bar",
    "field1": foo
}"; line: 3, column: 18]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2873)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2851)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken2(ReaderBasedJsonParser.java:2648)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2626)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchFalse(ReaderBasedJsonParser.java:2600)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:965)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:512)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
	at io.stargate.web.resources.v2.RowsResource.modifyRow(RowsResource.java:606)
	at io.stargate.web.resources.v2.RowsResource.lambda$updateRows$5(RowsResource.java:463)
	at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:37)
	at io.stargate.web.resources.v2.RowsResource.updateRows(RowsResource.java:461)
```

We need to either go through and wrap `mapper.readValue(payload, Map.class)` occurrences with a try-catch or catch it at the top in `io.stargate.web.resources.RequestHandler#handle`. The only problem with catching it at the top and returning the 400 is there might be a chance we'd incorrectly return 400 when it's actually a 500.

**Comment by ivansenic** [comment]
@dougwettlaufer We did a try/catch for those in the Docs API resources.. Point being that this is the only way to be certain that the exception comes from the bad user input and not somewhere during processing on our side.

**Comment by dougwettlaufer** [comment]
> @dougwettlaufer We did a try/catch for those in the Docs API resources.

I see it now, there's catch blocks for `JsonProcessingException` throughout that side of the module. I was searching for `JsonParseException` so I missed them.

**Comment by tatu-at-datastax** [comment]
Something worth considering: `JsonProcessingException` is the base type for all Jackson-originating problems; `JsonParseException` (one of subtypes) is explicitly about low-level JSON (and other formats) decoding.
So it may sense to handle parse exceptions separately from other `JsonProcessingException`s (or even `IOException`s, the ultimate base exception type).
