### ISSUE TITLE
DSE build fails with latest stargate-builder version

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1142]
When trying to update to the stargate-builder `v1.0.5` in the #1139, the [build](https://console.cloud.google.com/cloud-build/builds/b29af039-ab22-4aeb-9fb8-a77df1f50102?project=stargateio) fails on the normal tests with:

```
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-27 10:25:55,457 ProcessRunner.java:78 - storage0-0> WARN  [main] 2021-07-27 10:25:55,456  SimpleSeedProvider.java:65 - Seed provider couldn't lookup host 127.0.0.1:7000
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> Jul 27, 2021 10:25:55 AM com.google.inject.internal.MessageProcessor visit
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> INFO: An exception was caught and reported. Message: org.apache.cassandra.exceptions.ConfigurationException: The seed provider lists no seeds.
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> org.apache.cassandra.exceptions.ConfigurationException: The seed provider lists no seeds.
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> 	at org.apache.cassandra.config.DatabaseDescriptor.applySeedProvider(DatabaseDescriptor.java:1606)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> 	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:580)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> 	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:233)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,478 ProcessRunner.java:85 - storage0-0> 	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:254)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.datastax.bdp.DseCoreModule.<init>(DseCoreModule.java:83)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.datastax.bdp.DseModule.getRequiredModules(DseModule.java:161)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.datastax.bdp.server.AbstractDseModule.configure(AbstractDseModule.java:27)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.datastax.bdp.DseModule.configure(DseModule.java:88)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.spi.Elements.getElements(Elements.java:110)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.Guice.createInjector(Guice.java:96)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.Guice.createInjector(Guice.java:73)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.google.inject.Guice.createInjector(Guice.java:62)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.datastax.bdp.ioc.DseInjector.get(DseInjector.java:36)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 	at com.datastax.bdp.DseModule.main(DseModule.java:102)
Step #4 - "dse-6.8": ERROR [Exec Stream Pumper] 2021-07-27 10:25:55,479 ProcessRunner.java:85 - storage0-0> 
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-27 10:25:55,508 ProcessRunner.java:78 - storage0-0> ERROR [main] 2021-07-27 10:25:55,508  DseModule.java:108 - Exiting...
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-27 10:25:55,509 ProcessRunner.java:78 - storage0-0> com.google.inject.CreationException: Unable to create injector, see the following errors:
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-27 10:25:55,509 ProcessRunner.java:78 - storage0-0> 
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-27 10:25:55,509 ProcessRunner.java:78 - storage0-0> 1) An exception was caught and reported. Message: The seed provider lists no seeds.
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-27 10:25:55,509 ProcessRunner.java:78 - storage0-0>   at com.datastax.bdp.DseModule.configure(Unknown Source)
```

Doing some investigation shows that it's not working with `1.0.4` either (see #1141). Also in the f8073de we already reverted the builder from `1.0.4` to `1.0.3`. 

Most likely the build started to fail due to the DSE version upgrade from `6.8.5` to `6.8.9` in the #733.

As the effect we are still running test with `6.8.5` I guess.

**Comment by dimas-b** [comment]
I suspect a change on the `ccm` side. I did a fix for DSE seeds at some point (https://github.com/riptano/ccm/commit/d674d82d19a42a4e3214ae6cafc67dac6e2506c6)... could it have gone out of sync again?

**Comment by dimas-b** [comment]
IIRC, every time we rebuild the CI image, it pick up the latest `ccm` `master`.

**Comment by dimas-b** [comment]
I tested the latest `ccm` `master` with DSE 6.8.13 locally and it worked, so I do not really know what the problem might be.

**Comment by dimas-b** [comment]
By the way, the version of DSE is the CI image is irrelevant. We did this to try and save some download time, but the effect appears to be insignificant. It might be worth removing the pre-downloading of C* and DSE jars. The version that matters in set in integration tests (`testing/pom.xml`).

**Comment by ivansenic** [comment]
Then why the builder update makes and fail? This is the mvn target. not the builder pre-download of the jars?

**Comment by dimas-b** [comment]
I still think `ccm` is the most likely root cause, but I do not have anything solid ATM

**Comment by dimas-b** [comment]
Where is the source for the CI docker image?

**Comment by ivansenic** [comment]
> Where is the source for the CI docker image?

I guess it's the https://github.com/stargate/stargate/blob/master/ci/Dockerfile, or?

**Comment by ivansenic** [comment]
@dimas-b OK seems you are right, the Ci log says all nodes are in the `6.8.13`:

`Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-28 08:47:30,733 ProcessRunner.java:78 - storage0-0> INFO  [DSE main thread] 2021-07-28 08:47:30,733  CassandraDaemon.java:783 - All nodes in this cluster are on DSE version 6.8.13`

Now I am even more confused.

**Comment by jeffreyscarpenter** [comment]
@ivansenic can we close this?

**Comment by ivansenic** [comment]
A dinosaur leftover :) The builder already uses image `v1.0.14` so this does not apply anymore.
