### ISSUE TITLE
`json-schema` Endpoint: GET request returns 400 on a collection with a schema

### ISSUE THREAD

**Issue by kidrecursive** [stargate/stargate#1291]
Here is the error:
```json
{
  "description": "Bad request: argument \"content\" is null",
  "code": 400
}
```
Request was made using the Swagger UI

**Comment by ivansenic** [comment]
@kidrecursive Can you be more descriptive here, what endpoint you are hitting?

**Comment by kidrecursive** [comment]
Sure thing, it's a `GET` request on `json-schema`, the full path is: `/v2/namespaces/{namespace-id}/collections/{collection-id}/json-schema`

Also, verified that I get the same result from `postman`, `curl`, etc

**Comment by ivansenic** [comment]
@kidrecursive So I just tried this out and the response you are receiving is happening when you are executing that `GET` on a collection that does not have schema set. And yes it's another bug on our side, you should get a clear message that schema is not set for this collection, so either `204` or `404` with a message that schema does not exist. 

Good news is that if you set the schema successfully prior to making this call, the request is good.

```
INFO  [jersey-server-managed-async-executor-3] 2021-10-01 16:55:18,798 RequestHandler.java:49 - Bad request
java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4429)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2718)
	at io.stargate.web.docsapi.service.JsonSchemaHandler.getJsonSchemaForCollection(JsonSchemaHandler.java:76)
	at io.stargate.web.docsapi.resources.JsonSchemaResource.lambda$getJsonSchema$1(JsonSchemaResource.java:121)
	at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:37)
	at io.stargate.web.docsapi.resources.JsonSchemaResource.getJsonSchema(JsonSchemaResource.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.lambda$apply$0(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2$1.run(ServerRuntime.java:816)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2.run(ServerRuntime.java:811)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  [jersey-server-managed-async-executor-3] 2021-10-01 16:55:18,804 Slf4jRequestLogWriter.java:62 - 127.0.0.1 - - [01/Oct/2021:14:55:18 +0000] "GET /v2/namespaces/docs_crud_basic/collections/large/json-schema HTTP/1.1" 400 70 "-" "curl/7.68.0" 9
```
I'll fix asap.
