### ISSUE TITLE
TracingQueryTest flaky on DSE builds

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1388]
I have seen already a few times the same reason for the failing DSE build:

```
Step #4 - "dse-6.8": INFO  [main] 2021-11-02 10:35:30,917 ExternalStorage.java:311 - Storage cluster (version 6.8) that was requested by [engine:junit-jupiter]/[class:io.stargate.it.http.graphql.cqlfirst.MetricsTest] has been removed.
Step #4 - "dse-6.8": [INFO] 
Step #4 - "dse-6.8": [INFO] Results:
Step #4 - "dse-6.8": [INFO] 
Step #4 - "dse-6.8": [ERROR] Failures: 
Step #4 - "dse-6.8": [ERROR]   TracingQueryTest.tracingIdNormalQueryEnabledGetTracingData:180->validateTrace:214 
Step #4 - "dse-6.8": Expecting:
Step #4 - "dse-6.8":  <0L>
Step #4 - "dse-6.8": to be greater than:
Step #4 - "dse-6.8":  <0L> 
Step #4 - "dse-6.8": [INFO] 
Step #4 - "dse-6.8": [ERROR] Tests run: 1000, Failures: 1, Errors: 0, Skipped: 4
```

Seems that something is wrong here and we should have a look.

**Comment by ivansenic** [comment]
Seems that failure occurs because of the exception in the test setup:

```
/[method:tracingIdBatchQueryDisabled(com.datastax.oss.driver.api.core.CqlIdentifier)]
Step #4 - "dse-6.8": Nov 18, 2021 8:10:26 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
Step #4 - "dse-6.8": SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=177, target=127.0.2.37:8090} was not shutdown properly!!! ~*~*~*
Step #4 - "dse-6.8":     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
Step #4 - "dse-6.8": java.lang.RuntimeException: ManagedChannel allocation site
Step #4 - "dse-6.8": 	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
Step #4 - "dse-6.8": 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
Step #4 - "dse-6.8": 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
Step #4 - "dse-6.8": 	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:612)
Step #4 - "dse-6.8": 	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
Step #4 - "dse-6.8": 	at io.stargate.it.grpc.GrpcIntegrationTest.setup(GrpcIntegrationTest.java:59)
Step #4 - "dse-6.8": 	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
Step #4 - "dse-6.8": 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #4 - "dse-6.8": 	at java.lang.reflect.Method.invoke(Method.java:498)
Step #4 - "dse-6.8": 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:490)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$19(ClassBasedTestDescriptor.java:475)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:167)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:164)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
Step #4 - "dse-6.8": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
Step #4 - "dse-6.8": 	at java.util.ArrayList.forEach(ArrayList.java:1259)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
Step #4 - "dse-6.8": 	at java.util.ArrayList.forEach(ArrayList.java:1259)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
Step #4 - "dse-6.8": 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
Step #4 - "dse-6.8": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
Step #4 - "dse-6.8": 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
Step #4 - "dse-6.8": 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
Step #4 - "dse-6.8": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
Step #4 - "dse-6.8": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
Step #4 - "dse-6.8": 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
Step #4 - "dse-6.8": 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
Step #4 - "dse-6.8": 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
Step #4 - "dse-6.8": 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
Step #4 - "dse-6.8": 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
Step #4 - "dse-6.8": 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
