### ISSUE TITLE
NoClassDefFoundError in auth-table-based-service for Strings

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#144]
Seeing this in the logs

```
ERROR [2020-09-24 12:58:03,664] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: a1f4782a7d11bc24
! java.lang.NoClassDefFoundError: com/datastax/oss/driver/shaded/guava/common/base/Strings
! at io.stargate.auth.table.AuthTableBasedService.validateToken(AuthTableBasedService.java:209)
! at io.stargate.web.resources.Db.getDataStoreForToken(Db.java:77)
! at io.stargate.web.resources.RowResource.lambda$addRow$4(RowResource.java:250)
! at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:37)
! at io.stargate.web.resources.RowResource.addRow(RowResource.java:248)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by dougwettlaufer** [comment]
Closing as this is no longer an issue. I grepped the logs from CI and this error no longer shows up.
