### ISSUE TITLE
Failure if trying to create User-Defined Type (UDT) with mixed-case name, using REST API

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1538]
Attempt to create a UDT with name like `udtType` fail with message:

```
{"description":"Bad request: Malformed type name: testUdt","code":400}
```

which is probably due to missing quoting by query builder (failure seems to come from `Column` class of `persistence-api`).

**Comment by tatu-at-datastax** [comment]
Relevant stack trace seems to be:

```
java.lang.IllegalArgumentException: Malformed type name (requires quoting but is not quoted): testUDT
 	at io.stargate.db.schema.Column$Type.fromCqlDefinitionOf(Column.java:590)
 	at io.stargate.db.schema.Column$Type.fromCqlDefinitionOf(Column.java:551)
 	at io.stargate.web.restapi.resources.v2.schemas.TablesResource.lambda$createTable$2(TablesResource.java:256)
```

but it is not quite clear how quoting should be applied here since the last line is:

```
            ColumnType type = Type.fromCqlDefinitionOf(keyspace, colDef.getTypeDefinition());
```

and simply uses name from `ColumnDefinition` that user provides (which should not need to be escaped).

**Comment by tatu-at-datastax** [comment]
Removing particular validation statement (`Column`, line 599) will resolve the issue and does not seem to cause new failures. While I am hesitant to just remove checks, this one seems like it might be incorrectly trying to validate condition that should not exist: `QueryBuilder` itself should likely apply quoting if necessary?
