### ISSUE TITLE
gRPC tests failing in CI (looks to be v2 only)

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1568]
Several different gRPC tests are failing in CI. As far as I'm aware these are not failing when run on local developer machines.

Speculation: Starting to think the issue has to with `SchemaNotificationsHandler` trying to send something to the client after the server is in shutdown?

The error comes from `grpc-java` here: https://github.com/grpc/grpc-java/blob/v1.42.1/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L214

Failing tests:
```
Step #4 - "cassandra-4.0": [ERROR]   CollectionsTest ? Server com.google.common.util.concurrent.UncheckedExecutionE...
Step #4 - "cassandra-4.0": [ERROR]   ExecuteBatchTest ? Server com.google.common.util.concurrent.UncheckedExecution...
Step #4 - "cassandra-4.0": [ERROR]   ExecuteBatchTest.simpleBatchAfterSchemaChange:116 ? StatusRuntime INTERNAL: co...
Step #4 - "cassandra-4.0": [ERROR]   ExecuteQueryTest ? Server com.google.common.util.concurrent.UncheckedExecution...
```

Stacktrace looks like:

```
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> java.lang.IllegalStateException: call already closed
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:214)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:207)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.micrometer.core.instrument.binder.grpc.MetricCollectingServerCall.close(MetricCollectingServerCall.java:58)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:389)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.SchemaNotificationsHandler.onSchemaChange(SchemaNotificationsHandler.java:69)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.SchemaNotificationsHandler.onDropKeyspace(SchemaNotificationsHandler.java:135)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.db.cassandra.impl.EventListenerWrapper.onDropKeyspace(EventListenerWrapper.java:81)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,980 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.lambda$notifyDropKeyspace$43(Schema.java:850)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.notifyDropKeyspace(Schema.java:850)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.dropKeyspace(Schema.java:737)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at java.lang.Iterable.forEach(Iterable.java:75)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.merge(Schema.java:655)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.transform(Schema.java:602)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.MigrationManager.lambda$announce$2(MigrationManager.java:226)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at java.lang.Thread.run(Thread.java:748)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> ERROR [Native-Transport-Requests-4] 2022-01-20 02:30:25,979 ErrorMessage.java:457 - Unexpected exception during request
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: call already closed
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1262)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1248)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.MigrationManager.announce(MigrationManager.java:228)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.statements.schema.AlterSchemaStatement.execute(AlterSchemaStatement.java:102)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.statements.schema.DropKeyspaceStatement.execute(DropKeyspaceStatement.java:30)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.statements.schema.AlterSchemaStatement.execute(AlterSchemaStatement.java:54)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.statements.schema.DropKeyspaceStatement.execute(DropKeyspaceStatement.java:30)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:222)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.QueryProcessor.processPrepared(QueryProcessor.java:520)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,981 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.cql3.QueryProcessor.processPrepared(QueryProcessor.java:498)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.db.cassandra.impl.StargateQueryHandler.processPrepared(StargateQueryHandler.java:184)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.transport.messages.ExecuteMessage.execute(ExecuteMessage.java:138)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.transport.Message$Request.execute(Message.java:242)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.db.cassandra.impl.Cassandra40Persistence$Cassandra40Connection.lambda$executeRequestOnExecutor$0(Cassandra40Persistence.java:449)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.db.cassandra.impl.Cassandra40Persistence.lambda$runOnExecutor$1(Cassandra40Persistence.java:265)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:119)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at java.lang.Thread.run(Thread.java:748)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> Caused by: java.lang.IllegalStateException: call already closed
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:214)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:207)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.micrometer.core.instrument.binder.grpc.MetricCollectingServerCall.close(MetricCollectingServerCall.java:58)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:389)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.SchemaNotificationsHandler.onSchemaChange(SchemaNotificationsHandler.java:69)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.SchemaNotificationsHandler.onDropKeyspace(SchemaNotificationsHandler.java:135)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.db.cassandra.impl.EventListenerWrapper.onDropKeyspace(EventListenerWrapper.java:81)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,982 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.lambda$notifyDropKeyspace$43(Schema.java:850)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.notifyDropKeyspace(Schema.java:850)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.dropKeyspace(Schema.java:737)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at java.lang.Iterable.forEach(Iterable.java:75)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.merge(Schema.java:655)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.Schema.transform(Schema.java:602)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.schema.MigrationManager.lambda$announce$2(MigrationManager.java:226)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2022-01-20 02:30:25,983 ProcessRunner.java:78 - stargate0-0> 	... 2 common frames omitted
Step #4 - "cassandra-4.0": WARN  [main] 2022-01-20 02:30:25,986 ExternalStorage.java:153 - Test error in [engine:junit-jupiter]/[class:io.stargate.it.grpc.ExecuteBatchTest]/[method:simpleBatchAfterSchemaChange()]
Step #4 - "cassandra-4.0": io.grpc.StatusRuntimeException: INTERNAL: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: call already closed
Step #4 - "cassandra-4.0": 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
Step #4 - "cassandra-4.0": 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
Step #4 - "cassandra-4.0": 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
Step #4 - "cassandra-4.0": 	at io.stargate.proto.StargateGrpc$StargateBlockingStub.executeQuery(StargateGrpc.java:531)
Step #4 - "cassandra-4.0": 	at io.stargate.it.grpc.ExecuteBatchTest.simpleBatchAfterSchemaChange(ExecuteBatchTest.java:116)
Step #4 - "cassandra-4.0": 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #4 - "cassandra-4.0": 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #4 - "cassandra-4.0": 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #4 - "cassandra-4.0": 	at java.lang.reflect.Method.invoke(Method.java:498)
Step #4 - "cassandra-4.0": 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
Step #4 - "cassandra-4.0": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
Step #4 - "cassandra-4.0": 	at java.util.ArrayList.forEach(ArrayList.java:1259)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
Step #4 - "cassandra-4.0": 	at java.util.ArrayList.forEach(ArrayList.java:1259)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
Step #4 - "cassandra-4.0": 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
Step #4 - "cassandra-4.0": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
Step #4 - "cassandra-4.0": 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
Step #4 - "cassandra-4.0": 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
Step #4 - "cassandra-4.0": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
Step #4 - "cassandra-4.0": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
Step #4 - "cassandra-4.0": 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
Step #4 - "cassandra-4.0": 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
Step #4 - "cassandra-4.0": 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
Step #4 - "cassandra-4.0": 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
Step #4 - "cassandra-4.0": 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
Step #4 - "cassandra-4.0": 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
````

**Comment by mpenick** [comment]
Possibly fixed by: https://github.com/stargate/stargate/pull/1564

**Comment by tatu-at-datastax** [comment]
Dup of #1580, closing.
