### ISSUE TITLE
Invalid UUID (0 bytes) served by gRPC for SGv2/REST API

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1577]
Our perf tests for StargateV2/REST seem to have odd failures reported when accessing rows inserted: stack trace:

```
ERROR [dw-176 - GET /v2/keyspaces/baselines/iot?where=%7B%22machine_id%22%3A%7B%22%24eq%22%3A%2212d1012c-47fa-441c-a41e-87
3c048d2535%22%7D%2C%22sensor_name%22%3A%7B%22%24eq%22%3A%22wire_gauge%22%7D%7D&page-size=10] 2022-01-24 11:53:00,025 Defau
ltExceptionMapper.java:59 - Error handling a request: f9a67463d3518a01
java.lang.IllegalArgumentException: Expected 16 bytes for a uuid values, got 0
        at io.stargate.grpc.Values.uuid(Values.java:258)
        at io.stargate.sgv2.restsvc.grpc.FromProtoValueCodecs$UUIDCodec.fromProtoValue(FromProtoValueCodecs.java:368)
        at io.stargate.sgv2.restsvc.grpc.FromProtoConverter.mapFromProtoValues(FromProtoConverter.java:41)
        at io.stargate.sgv2.restsvc.resources.ResourceBase.convertRows(ResourceBase.java:157)
        at io.stargate.sgv2.restsvc.resources.ResourceBase.fetchRows(ResourceBase.java:146)
        at io.stargate.sgv2.restsvc.resources.Sgv2RowsResourceImpl.getRowWithWhere(Sgv2RowsResourceImpl.java:114)
```

which suggests that somehow either entries are stored incorrectly (corrupt data), or, perhaps more likely, that gRPC API is changing missing/null value into incorrect representation.

I have not been able to reproduce the issue with regular POSTs via REST API; data in this case is generated by Fallout tests, but not sure if it's via straight CQL or REST (sgv2) API.

Tests are here:

https://fallout.sjc.dsinternal.org/tests/ui/jenkins-dse@datastax.com/sgv2-http-rest-timeseries-cass4

**Comment by EricBorczuk** [comment]
I was able to reproduce this locally by running the relevant NoSQLBench test workload with a high (1 million) cycle count, and found that the UUID value of `113fbac2-0cad-40f8-940c-6a95f8d1a4cf` for some reason is not parsed correctly. It gets converted after a certain point to a 0 byte default UUID value because the data from C* sent over the wire is invalid for some reason

**Comment by tatu-at-datastax** [comment]
Some more progress: with #1586 it looks like failure comes from gRPC server. Stack trace (via Integration Tests), when triggered, looks like:

```
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> ERROR [Native-Transport-Requests-1] 2022-01-27 13:07:10,023 ExceptionHandler.java:70 - Unhandled error returning UNKNOWN to the client
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> java.lang.IllegalArgumentException: Expected 16 bytes for a UUID, got 0
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.codec.UuidCodec.decode(UuidCodec.java:47)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.codec.ValueCodec.decodeValue(ValueCodec.java:62)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.ValuesHelper.processResult(ValuesHelper.java:152)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.ValuesHelper.processResult(ValuesHelper.java:123)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.QueryHandler.buildResponse(QueryHandler.java:106)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,024 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.grpc.service.MessageHandler.lambda$handleUnprepared$2(MessageHandler.java:235)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at io.stargate.db.cassandra.impl.Cassandra311Persistence.lambda$runOnExecutor$1(Cassandra311Persistence.java:286)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134)
INFO  [Exec Stream Pumper] 2022-01-27 13:07:10,025 ProcessRunner.java:78 - stargate0-0> 	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:1
```
