### ISSUE TITLE
`io.netty.util.IllegalReferenceCountException` caused by `HAProxyMessage.release()`

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1941]
Noticed this error in CNDB tests:

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
	at io.netty.handler.codec.haproxy.HAProxyMessage.release(HAProxyMessage.java:578)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.channelRead(HAProxyMessageDecoder.java:228)
```

Adding `HAProxyMessage.release()` was suppose to fix the error in this issue: https://github.com/stargate/stargate/issues/1397, but this this is causing an invalid reference count.

I think this should be rolled back: https://github.com/stargate/stargate/pull/1910, this is seems to be incorrect.

**Comment by mpenick** [comment]
From: https://netty.io/4.0/api/io/netty/channel/SimpleChannelInboundHandler.html

> Be aware that depending of the constructor parameters it will release all handled messages by passing them to [ReferenceCountUtil.release(Object)](https://netty.io/4.0/api/io/netty/util/ReferenceCountUtil.html#release-java.lang.Object-). In this case you may need to use [ReferenceCountUtil.retain(Object)](https://netty.io/4.0/api/io/netty/util/ReferenceCountUtil.html#retain-T-) if you pass the object to the next handler in the [ChannelPipeline](https://netty.io/4.0/api/io/netty/channel/ChannelPipeline.html).

I should have read the docs better, but I'm still not sure what happening with: https://github.com/stargate/stargate/issues/1397
