### ISSUE TITLE
Paging state can not be created in some cases for the Docs V2

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1946]
Hitting the following exception:

```
2022-07-04 13:41:15,282 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: ERROR [Native-Transport-Requests-2] 2022-07-04 11:41:15,282 ExceptionHandler.java:82 - Unhandled error returning UNKNOWN to the client
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: java.lang.IllegalArgumentException: Required value is not present in current row (table: OWB3z55n07g9AjJA, column: p2)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.db.PagingPosition.requiredValue(PagingPosition.java:75)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.db.cassandra.impl.Conversion.lambda$toPagingState$1(Conversion.java:158)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.db.cassandra.impl.Conversion.toPagingState(Conversion.java:159)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.db.cassandra.impl.Cassandra40Persistence$Cassandra40Connection.makePagingState(Cassandra40Persistence.java:534)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.bridge.service.QueryHandler.getPagingStateFromRow(QueryHandler.java:162)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.bridge.service.ValuesHelper.processResult(ValuesHelper.java:191)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.bridge.service.ValuesHelper.processResult(ValuesHelper.java:151)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.bridge.service.QueryHandler.buildResponse(QueryHandler.java:124)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.bridge.service.MessageHandler.lambda$handleUnprepared$2(MessageHandler.java:238)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.stargate.db.cassandra.impl.Cassandra40Persistence.lambda$runOnExecutor$1(Cassandra40Persistence.java:272)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2022-07-04 13:41:15,283 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165)
2022-07-04 13:41:15,284 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:137)
2022-07-04 13:41:15,284 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:119)
2022-07-04 13:41:15,284 INFO  [coordinator-docker] (docker-java-stream--673570111) STDOUT: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30
```

### Steps to reproduce:

1. Write 3 documents:
    a. `{"value": "a", "n": { "value": 5}}`
    b. `{"value": "a"}` 
    c. `{"value": "b", "n": { "value": 10}}`
2. Execute search in a collection with `where={"value": {"$in": ["a", "b"]}, "n.value": {"$nin": [10]}}`

**Comment by ivansenic** [comment]
Can not reproduce on the live running system.

**Comment by EricBorczuk** [comment]
Is it possible that the paging state is being generated from a row that was constructed in memory without required clustering column values? Maybe I made a mistake with `null` vs empty string someplace, will look tomorrow

**Comment by ivansenic** [comment]
Can not reproduce, close for now.
