### ISSUE TITLE
Documents API should handle `OverloadedException` gracefully

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1972]
(note: while this issue is specifically about Docs API, same/similar issues are very likely with REST and GraphQL APIs -- we'll file separate issues for those, as necessary)

Looking at our logs we noticed that there are error entries with stack trace, correlating to spikes in 500 responses for Documents API end points. Stack traces look like:

```
     Error when executing request
     java.util.concurrent.CompletionException: org.apache.cassandra.stargate.exceptions.OverloadedException: Rate limit reached, please consult our documentation at https://astra.dev/rate-limit
     	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
     	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
     	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
     	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
     	at io.stargate.db.datastore.PersistenceBackedDataStore.batch(PersistenceBackedDataStore.java:201)
     	at io.stargate.db.datastore.PersistenceBackedDataStore.batch(PersistenceBackedDataStore.java:190)
     	at io.stargate.db.query.AsyncQueryExecutor.batch(AsyncQueryExecutor.java:104)
     	at io.stargate.db.query.AsyncQueryExecutor.batch(AsyncQueryExecutor.java:82)
     	at io.stargate.web.docsapi.service.write.DocumentWriteService.executeBatch(DocumentWriteService.java:498)
     	at io.stargate.web.docsapi.service.write.DocumentWriteService.lambda$writeDocument$3(DocumentWriteService.java:125)
     	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
     	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:65)
     	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
     	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
     	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
     	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
     	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     	at java.base/java.lang.Thread.run(Thread.java:834)
     Caused by: org.apache.cassandra.stargate.exceptions.OverloadedException: Rate limit reached, please consult our documentation at https://astra.dev/rate-limit
 
```

This is from the current Stargate (V1), SGv2 probably has similar handling.

Instead of this exception propagating through, we should catch it and give caller something like `429` (Too Many Requests (RFC 6585)) so that it can reduce send rate.

**Comment by ivansenic** [comment]
Docs API is handling that exception in [ErrorHandler](https://github.com/stargate/stargate/blob/master/restapi/src/main/java/io/stargate/web/docsapi/resources/error/ErrorHandler.java).

**Comment by tatu-at-datastax** [comment]
Good fix @ivansenic! As per @olim7t 's comments it sounds like GraphQL should already handle these correctly (and DocsAPI was expected to, was just missing unwrapping). REST API appears to also have some related handling but to my knowledge no test(s) to verify. Would be great to add tests; will file an issue.
