### ISSUE TITLE
`NullPointerException` on the `RowResource`

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1994]
Stack trace after calling `POST /v1/keyspaces/ks1/tables/users/rows`:

```
     Internal error when executing request: java.lang.NullPointerException
     java.lang.NullPointerException: null
     	at io.stargate.web.restapi.resources.v1.RowResource.lambda$addRow$9(RowResource.java:425)
     	at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:35)
     	at io.stargate.web.restapi.resources.v1.RowResource.addRow(RowResource.java:420)
     	at jdk.internal.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
     	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
     	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
     	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
     	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
     	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
     	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
     	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
     	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
     	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
     	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
     	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
     	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
     	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
     	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
     	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
     	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
     	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
     	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
     	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
     	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
     	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
     	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
     	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
     	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
     	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
     	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
     	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
     	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
     	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
     	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
     	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
     	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
     	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
     	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
     	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
     	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
     	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
     	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
     	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
     	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
     	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
     	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
     	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
     	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
     	at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:38)
     	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:713)
     	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
     	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
     	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
     	at org.eclipse.jetty.server.Server.handle(Server.java:516)
     	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
     	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
     	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
     	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
     	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
     	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
     	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
     	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
     	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
     	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
     	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
     	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
     	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
     	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
     	at java.base/java.lang.Thread.run(Thread.java:834) 
```

Maybe `500` is reported instead of the `400`.

**Comment by tatu-at-datastax** [comment]
Since it's caught, logged at `RequestHandler`, line 108 (as per Splunk), we report generic 500 I think:

```
    } catch (Exception e) {
      // Do log underlying Exception with Stack trace since this is unknown, unexpected:
      logger.error("Internal error when executing request: " + e, e);
      return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
```

**Comment by maheshrajamani** [comment]
@tatu-at-datastax  This error happens when an empty json is sent as request body. Will add validation for the input objects.
`curl --location --request POST '127.0.0.2:8082/v1/keyspaces/{keyspace}/tables/{table}/rows' --header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{      
    }'  `
