### ISSUE TITLE
Metrics NPE in cql module

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#209]
Seeing this stacktrace when running queries 

```java
WARN  [2020-10-06 16:52:16,653] org.eclipse.jetty.server.HttpChannel: /metrics
! java.lang.NullPointerException: null
! at org.apache.cassandra.stargate.transport.internal.ConnectedClient.asMap(ConnectedClient.java:112)
! at org.apache.cassandra.stargate.metrics.ClientMetrics.connectedClients(ClientMetrics.java:131)
! at io.prometheus.client.dropwizard.DropwizardExports.fromGauge(DropwizardExports.java:62)
! at io.prometheus.client.dropwizard.DropwizardExports.collect(DropwizardExports.java:132)
! at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
! at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:154)
! at io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:141)
! at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:49)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
! at io.stargate.health.HealthCheckerAdminServlet.service(HealthCheckerAdminServlet.java:138)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at org.eclipse.jetty.server.Server.handle(Server.java:500)
! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
! at java.lang.Thread.run(Thread.java:748)
```

**Comment by tatu-at-datastax** [comment]
@mpenick Do we still see this? I am thinking of closing unless there are on-going Splunk events (I cannot find any) or if this happens to be easily reproducible somehow.

**Comment by ivansenic** [comment]
@tatu-at-datastax `ClientMetrics` were fully refactored by me, and the referenced code in the stack trace does not even exist anymore. You can close this as completed imo.
