### ISSUE TITLE
Bridge Metadata access fails during bootstrapping with `java.lang.IllegalStateException: No RESTEasy Reactive request in progress`

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2108]
With #2087 we no longer default to fallback values if the initial Bridge call to fetch metadata fails. This exposed a seeming error in the implementation of the access call: failure appears to be:

```
2022-09-28 12:42:34,537 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalStateException: No RESTEasy Reactive request in progress
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.getContext(ContextProducers.java:138)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.securityContext(ContextProducers.java:132)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.securityContext$$superforward1(Unknown Source)
[LONG stack trace removed, reproduce with simple `../mvnw quarkus:dev` when Cassandra and Coordinator running]
```

This is odd as none of the tests (including one added as part of PR failed), but this is likely due to:

1. Mocked version having different context/threading and not trigger this issue
2. Existing Integration Tests being configuring to specifically skip metadata access (possibly since at some point functionality was not yet implemented)

At any rate, call fails and needs to be fixed to work.

**Comment by ivansenic** [comment]
This bug is most likely introduced by a new version of Quarkus that changes and has the request context containing some default beans.. Will post a fix for this..

However, with #2087 we are not able to start the app if the call fails, this changed the previous behavior we had.. We either have to:

* set `bridgeFallbackEnabled=true` so that the app starts by default and fallback
* or revert completely #2087

**Comment by ivansenic** [comment]
Done in #2115 and @2114.
