### ISSUE TITLE
InboundHAProxyHandler is not @Sharable

### ISSUE THREAD

**Issue by jakubzytka** [stargate/stargate#2232]
```
Caused by: io.netty.channel.ChannelPipelineException: org.apache.cassandra.stargate.transport.internal.HAProxyProtocolDetectingDecoder$InboundHAProxyHandler is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600)
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:300)
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290)
	at org.apache.cassandra.stargate.transport.internal.HAProxyProtocolDetectingDecoder.decode(HAProxyProtocolDetectingDecoder.java:76)
```
	

I'll submit a PR shortly...

**Comment by tatu-at-datastax** [comment]
Quick question: has something changed recently to trigger this?

**Comment by tatu-at-datastax** [comment]
@jakubzytka yes sorry, I should have read the background before asking -- it is pretty clear when I did that. Thank you for adding notes; I re-ran the test and merged.
