### ISSUE TITLE
Update DSE to 6.8.29

### ISSUE THREAD

**Issue by tiagomlalves** [stargate/stargate#2236]
A new version of DSE has been released and should be used.

See release notes for issues resolved: https://github.com/datastax/release-notes/blob/master/DSE_6.8_Release_Notes.md#release-notes-for-6829

**Comment by ivansenic** [comment]
@tiagomlalves We are catching errors like this in our V2 integration tests:

```
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: INFO  [CoreThread-0] 2022-11-23 10:09:59,931 InboundHandshakeHandler.java:353 - Failed to properly handshake with peer /172.18.0.2:41879. Closing the channel.
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Lz4FrameDecoder
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at org.apache.cassandra.net.async.NettyFactory.createLz4Decoder(NettyFactory.java:340)
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at org.apache.cassandra.net.async.InboundHandshakeHandler.setupMessagingPipeline(InboundHandshakeHandler.java:303)
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at org.apache.cassandra.net.async.InboundHandshakeHandler.handleMessagingStartResponse(InboundHandshakeHandler.java:293)
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at org.apache.cassandra.net.async.InboundHandshakeHandler.decode(InboundHandshakeHandler.java:107)
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491)
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:430)
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
```

Seems that `dse-db` has incomplete dependency list, as `Lz4FrameEncoder` and `Lz4FrameDecoder` could not be found in the transitive deps:

```
[INFO] |  |  +- io.netty:netty-all:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-dns:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-haproxy:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-memcache:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-mqtt:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-redis:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-smtp:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-socks:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-stomp:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-codec-xml:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-resolver-dns:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-transport-rxtx:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-transport-sctp:jar:4.1.78.1.dse:compile
[INFO] |  |  |  +- io.netty:netty-transport-udt:jar:4.1.78.1.dse:compile
[INFO] |  |  |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.78.1.dse:compile
```

**Comment by ivansenic** [comment]
@tiagomlalves UPDATE: seems you are missing the 

```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec</artifactId>
      <version>4.1.78.1.dse</version>
    </dependency>
```

**Comment by tatu-at-datastax** [comment]
One additional note: C*3.11 and C*4.0 backends seem to require older Netty version (4.1.75) that we use, so need to leave main level `netty.version` at that.

**Comment by ivansenic** [comment]
Done, but we still need to fix java-driver as described here: https://github.com/stargate/stargate/issues/2269
