### ISSUE TITLE
GraphQL gets a schema notification for non-existent keyspace

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#247]
Seeing a lot of these during CI:
```java
ERROR [MigrationStage:1] 2020-10-12 12:59:26,446 CustomGraphQLServlet.java:201 - Error while refreshing handler for keyspace ks_1602521960321_corruptPagingStateTest
java.lang.NullPointerException: null
	at io.stargate.graphql.schema.DmlSchemaBuilder.<init>(DmlSchemaBuilder.java:108)
	at io.stargate.graphql.schema.SchemaFactory.newDmlSchema(SchemaFactory.java:20)
	at graphql.kickstart.servlet.CustomGraphQLServlet.buildKeyspaceHandler(CustomGraphQLServlet.java:209)
	at graphql.kickstart.servlet.CustomGraphQLServlet.addOrReplaceKeyspaceHandler(CustomGraphQLServlet.java:198)
	at graphql.kickstart.servlet.CustomGraphQLServlet.onDropTable(CustomGraphQLServlet.java:295)
	at io.stargate.db.cassandra.impl.EventListenerWrapper.onDropTable(EventListenerWrapper.java:116)
	at org.apache.cassandra.schema.Schema.lambda$notifyDropTable$44(Schema.java:868)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at org.apache.cassandra.schema.Schema.notifyDropTable(Schema.java:868)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.cassandra.schema.Schema.dropKeyspace(Schema.java:748)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.cassandra.schema.Schema.merge(Schema.java:668)
	at org.apache.cassandra.schema.Schema.transform(Schema.java:615)
	at org.apache.cassandra.schema.MigrationManager.lambda$announce$2(MigrationManager.java:353)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
The GraphQL servlet gets a notification that something changed in a keyspace, but upon loading that keyspace from the datastore it's not there.

First we need to gracefully handle the case `keyspace == null`, e.g. log a warning.

But second this should not happen, we need to figure out what's wrong. Could be a case-sensitivity issue, also I assume the keyspace name would be in internal form on both sides.

**Comment by olim7t** [comment]
Fixed in #316
