### ISSUE TITLE
StarterTest - SetStargatePropertiesWithBadHostSeedNode

### ISSUE THREAD

**Issue by jeffbanks** [stargate/stargate#26]
Seeing this issue on Windows running Java 14.  This test fails on an expected exception for the incorrect seed list entry of "datasta.cmo".  All other tests are running successful for the StarterTest.

org.opentest4j.AssertionFailedError: Expected setStargateProperties() to throw RuntimeException ==> Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:41)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2968)
	at io.stargate.starter.StarterTest.testSetStargatePropertiesWithBadHostSeedNode(StarterTest.java:52)

**Comment by dougwettlaufer** [comment]
Hi @jeffbanks, due to the C* and DSE libraries we use we're currently limited to only Java 8.

**Comment by jeffbanks** [comment]
Closing as this was issue with Java version being used.
