### ISSUE TITLE
NPE in `persistence-dse-6.8` class `Conversion.java` (line 580)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2623]
Looks like there is an NPE from DSE-6.8 backend, on line 580 (method `toResultInternal()`), observed in a production setting. 

Partial stack trace:

```
ERROR [CoreThread-1] 2023-06-15 08:37:02,753 Conversion.java:609 - Unexpected error thrown by persistence
java.lang.NullPointerException: null
        at io.stargate.db.dse.impl.Conversion.toResultInternal(Conversion.java:580)
        at io.stargate.db.dse.impl.Conversion.toResult(Conversion.java:554)
        at io.stargate.db.dse.impl.DsePersistence$DseConnection.lambda$executeRequest$1(DsePersistence.java:574)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
```

Line itself (if line numbers from stack trace match latest sources) would be:

```
            toResultMetadata(prepared.resultMetadata, null),
```

within:

```
      case PREPARED:
        ResultMessage.Prepared prepared = (ResultMessage.Prepared) resultMessage;
        PreparedWithInfo preparedWithInfo = (PreparedWithInfo) prepared;
        QueryHandler.Prepared preparedStatement =
            QueryProcessor.instance.getPrepared(prepared.statementId);
        return new Result.Prepared(
            Conversion.toExternal(prepared.statementId),
            Conversion.toExternal(prepared.resultMetadataId),
            toResultMetadata(prepared.resultMetadata, null),
            toPreparedMetadata(
                prepared.metadata.names,
                preparedStatement.statement.getPartitionKeyBindVariableIndexes()),
            preparedWithInfo.isIdempotent(),
            preparedWithInfo.isUseKeyspace());
```

but that doesn't make sense -- maybe line numbers are off, and they are not running from latest in `v1`? -- since if `prepared` was `null` it should already fail on line 576?!

**EDIT**: earlier fix #2552 was for seemingly similar (NPE) issue.

**Comment by tatu-at-datastax** [comment]
Actually, looking at this, I suspect NPE comes from 3 lines down, 583:

```
            toPreparedMetadata(
                prepared.metadata.names,
                preparedStatement.statement.getPartitionKeyBindVariableIndexes()),
```

so that `preparedStatement` was null, because it is obtained earlier by:

```
        QueryHandler.Prepared preparedStatement =
            QueryProcessor.instance.getPrepared(prepared.statementId);
```

which is similar to code in `StargateQueryHandler` that was fixed in #2552.

The problem, big one, is that of how to reproduce this problem. Fix itself might be same, but does it resolve the problem?

**Comment by tatu-at-datastax** [comment]
@ivansenic I was hoping you might have an idea of how similar fix could be applied (assuming you agree that makes sense).

**Comment by tatu-at-datastax** [comment]
@ivansenic Fix looks good, so even tho I am not 100% sure what's up with line number (could be I read it wrong somehow), I think that should solve the actual problem. Especially as C*3/4 backends already did that.
