### ISSUE TITLE
DSE persistence does not support SAI indexes

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#298]
Stargate on 127.0.0.2, with a DSE 6.8.4 backend on 127.0.0.1.

Connect to the backend directly, create a table with an SAI index:
```
cqlsh 127.0.0.1 9042
cqlsh_backend> create keyspace test WITH replication = {'class': 'SimpleStrategy' , 'replication_factor': 1};
cqlsh_backend> create table test.bar(k int primary key, m map<int,text>);
cqlsh_backend> create custom index t on test.bar(m) using 'StorageAttachedIndex';
```
Index queries work as expected:
```
cqlsh_backend> insert into test.bar(k,m) values(1,{1:'a'});
cqlsh_backend> select * from test.bar where m contains 'a';

 k | m
---+----------
 1 | {1: 'a'}

(1 rows)

```
But an error popped up in the Stargate log during the `CREATE INDEX` statement:
```
ERROR [MigrationStage:1] 2020-10-20 18:40:25,170 VerbHandlers.java:76 - Unexpected error during execution of request SCHEMA.PUSH (-1): /127.0.0.1 -> /127.0.0.2
org.apache.cassandra.exceptions.InvalidRequestException: Complex columns are not yet supported by storage-attached indexes.
        at com.datastax.bdp.index.StorageAttachedIndex.validateOptions(StorageAttachedIndex.java:303)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cassandra.schema.IndexMetadata.validateCustomIndexOptions(IndexMetadata.java:216)
        at org.apache.cassandra.schema.IndexMetadata.validate(IndexMetadata.java:132)
        at org.apache.cassandra.schema.Indexes.lambda$validate$2(Indexes.java:168)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.cassandra.schema.Indexes.validate(Indexes.java:168)
        at org.apache.cassandra.schema.TableMetadata.validate(TableMetadata.java:512)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.cassandra.schema.KeyspaceMetadata.validate(KeyspaceMetadata.java:112)
        at org.apache.cassandra.schema.KeyspaceMetadata.<init>(KeyspaceMetadata.java:85)
        at org.apache.cassandra.schema.KeyspaceMetadata.create(KeyspaceMetadata.java:167)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:1154)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspaces(SchemaKeyspace.java:1769)
        at org.apache.cassandra.schema.SchemaManager.merge(SchemaManager.java:893)
        at org.apache.cassandra.schema.SchemaManager.mergeAndAnnounceVersion(SchemaManager.java:877)
        at org.apache.cassandra.schema.SchemaVerbs.lambda$new$4(SchemaVerbs.java:126)
        at org.apache.cassandra.net.VerbHandlers$OneWay.handle(VerbHandlers.java:91)
        at org.apache.cassandra.net.Request.execute(Request.java:244)
        at org.apache.cassandra.net.OneWayRequest.execute(OneWayRequest.java:67)
        at org.apache.cassandra.net.MessageDeliveryTask$RequestDeliveryTask.deliverMessage(MessageDeliveryTask.java:84)
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:65)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.cassandra.concurrent.DebuggableThreadPoolExecutor$LocalSessionWrapper.run(DebuggableThreadPoolExecutor.java:332)
...
```
Also, the same index query doesn't work through Stargate CQL:
```
cqlsh 127.0.0.2 9042
cqlsh_stargate> select * from test.bar where m contains 'a';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
```
Restart the Stargate process.

Now the keyspace is not queryable at all through Stargate CQL:
```
cqlsh 127.0.0.2 9042
cqlsh_stargate> select * from test.bar where m contains 'a';
InvalidRequest: Error from server: code=2200 [Invalid query] message="keyspace test does not exist"
```

**Comment by mpenick** [comment]
@olim7t Do we need to upgrade stargate's dependency to use a more up-to-date version of DSE ?

**Comment by olim7t** [comment]
Indeed. Upgrading to 6.8.5 fixes it.
