### ISSUE TITLE
Error Connecting to Server's Cassandra from Local System via Stargate

### ISSUE THREAD

**Issue by jaypanchalnexus** [stargate/stargate#3036]
I have cloned this repository and am trying to connect to my server's Cassandra from my local system. 
I am using the command ./start_cass_311_dev_mode.sh to start Stargate. Additionally, 
I have verified that my Cassandra instance is running, but I am encountering the following error:

```
ERROR: Bundle io.stargate.db.cassandra_3_11 [1] EventDispatcher: Error during dispatch. (io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11)

io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:187)
        at io.stargate.core.activator.BaseActivator.access$900(BaseActivator.java:42)
        at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:230)
        at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:206)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:180)
        at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:103)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
        at io.stargate.starter.Starter.start(Starter.java:466)
        at io.stargate.starter.Starter.cli(Starter.java:669)
        at io.stargate.starter.Starter.main(Starter.java:708)
Caused by: java.lang.RuntimeException: Unable to gossip with any peers
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1603)
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:720)
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:980)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:837)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:786)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:395)
        at org.apache.cassandra.service.CassandraDaemon.init(CassandraDaemon.java:522)
        at io.stargate.db.cassandra.impl.Cassandra311Persistence.initializePersistence(Cassandra311Persistence.java:205)
        at io.stargate.db.cassandra.impl.Cassandra311Persistence.initializePersistence(Cassandra311Persistence.java:106)
        at io.stargate.db.datastore.common.AbstractCassandraPersistence.initialize(AbstractCassandraPersistence.java:106)
        at io.stargate.db.cassandra.Cassandra311PersistenceActivator.createService(Cassandra311PersistenceActivator.java:174)
        at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:243)
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:175)
        ... 25 more
io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:187)
        at io.stargate.core.activator.BaseActivator.access$900(BaseActivator.java:42)
        at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:230)
        at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:206)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:180)
        at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:103)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
        at io.stargate.starter.Starter.start(Starter.java:466)
        at io.stargate.starter.Starter.cli(Starter.java:669)
        at io.stargate.starter.Starter.main(Starter.java:708)
Caused by: java.lang.RuntimeException: Unable to gossip with any peers
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1603)
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:720)
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:980)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:837)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:786)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:395)
        at org.apache.cassandra.service.CassandraDaemon.init(CassandraDaemon.java:522)
        at io.stargate.db.cassandra.impl.Cassandra311Persistence.initializePersistence(Cassandra311Persistence.java:205)
        at io.stargate.db.cassandra.impl.Cassandra311Persistence.initializePersistence(Cassandra311Persistence.java:106)
        at io.stargate.db.datastore.common.AbstractCassandraPersistence.initialize(AbstractCassandraPersistence.java:106)
        at io.stargate.db.cassandra.Cassandra311PersistenceActivator.createService(Cassandra311PersistenceActivator.java:174)
        at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:243)
        at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:175)
        ... 25 more

ERROR [StorageServiceShutdownHook] 2024-12-20 07:03:49,573 CassandraDaemon.java:244 - Exception in thread Thread[StorageServiceShutdownHook,5,main]
java.lang.NoClassDefFoundError: ch/qos/logback/core/hook/DelayingShutdownHook
        at org.apache.cassandra.utils.logging.LogbackLoggingSupport.onShutdown(LogbackLoggingSupport.java:88)
        at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:821)
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
        at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.hook.DelayingShutdownHook not found by io.stargate.db.cassandra_3_11 [1]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 6 common frames omitted

```

my "docker-compose-dev-mode.yml" file code:
(Note: my cassandra.yaml file and this file configuration is same).

```
services:
  coordinator:
    image: stargateio/coordinator-3_11:${SGTAG}
    networks:
      - stargate
    ports:
      - "9042:9042"
      - "8081:8081"
      - "8090:8090"
    mem_limit: 2G
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    environment:
      - JAVA_OPTS="-Xmx1536M"
      - CLUSTER_NAME="Test Cluster"
      - CLUSTER_VERSION=3.11
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
      - DEVELOPER_MODE=false
      - CLUSTER_CONTACT_POINTS=<SERVER_IP> # Replace with 127.0.0.1 for Linux
      - SEED=<SERVER_IP> # Same as CLUSTER_CONTACT_POINTS
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    healthcheck:
      test: curl -f http://localhost:8084/checker/readiness || exit 1
      interval: 15s
      timeout: 10s
      retries: 10

  restapi:
    image: stargateio/restapi:${SGTAG}
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8082:8082"
    mem_limit: 2G
    environment:
      - QUARKUS_HTTP_CORS=true
      - QUARKUS_HTTP_CORS_ORIGINS=*
      - QUARKUS_HTTP_CORS_METHODS=POST,GET,PUT,OPTIONS,DELETE
      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091

  graphqlapi:
    image: stargateio/graphqlapi:${SGTAG}
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8080:8080"
    mem_limit: 2G
    environment:
      - QUARKUS_HTTP_CORS=true
      - QUARKUS_HTTP_CORS_ORIGINS=*
      - QUARKUS_HTTP_CORS_METHODS=POST,GET,PUT,OPTIONS,DELETE
      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091

networks:
  stargate:
```

here is my cassandra.yaml file config:
```
cluster_name: 'Test Cluster'
broadcast_address: <SERVER_IP>
broadcast_rpc_address: <SERVER_IP>
seed_provider:

    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "<SERVER_IP>"
listen_address: <SERVER_IP>
rpc_address: 0.0.0.0

```

Here is my "cassandra-rackdc.properties" file:
```
dc=datacenter1
rack=rack1
```

**Comment by jeffreyscarpenter** [comment]
Sounds like the stargate container is unable to access the host network. If you are providing the host's IP address (not localhost/127.0.0.1) as a contact point it should work.

**Comment by jaypanchalnexus** [comment]
I also tried using my host's IP address (instead of localhost/127.0.0.1), but the issue still persists.
