### ISSUE TITLE
GraphQL schema processing error in CI (shouldSupportSingleMutationWithAtomicDirective)

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#365]
```
Step #7 - "dse-6.8": INFO  [main] 2020-11-02 14:05:01,336 ExternalStorage.java:106 - About to run [engine:junit-jupiter]/[class:io.stargate.it.http.GraphqlTest]/[method:shouldSupportSingleMutationWithAtomicDirective()] with storage cluste
r version 6.8
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,388 StargateContainer.java:348 - sg0-0> ERROR [qtp1841489011-532] 2020-11-02 14:05:01,388 CustomGraphQLServlet.java:96 - Error initializing the GraphQL schema
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0> graphql.AssertException: All types within a GraphQL schema must have unique names. No two provided types may have the same name.
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0> No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0> You have redefined the type 'BUdt' from being a 'GraphQLObjectType' to a 'GraphQLObjectType'
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLTypeCollectingVisitor.assertTypeUniqueness(GraphQLTypeCollectingVisitor.java:105)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLTypeCollectingVisitor.visitGraphQLObjectType(GraphQLTypeCollectingVisitor.java:38)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLObjectType.accept(GraphQLObjectType.java:199)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:72)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.util.Traverser.traverse(Traverser.java:144)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:59)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:51)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:38)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaUtil.allTypes(SchemaUtil.java:48)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:111)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:40)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:529)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:515)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at io.stargate.graphql.schema.DmlSchemaBuilder.build(DmlSchemaBuilder.java:141)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at io.stargate.graphql.schema.SchemaFactory.newDmlSchema(SchemaFactory.java:18)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet$RequestHandlerReference.computeHandler(CustomGraphQLServlet.java:344)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet$RequestHandlerReference.get(CustomGraphQLServlet.java:335)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet.handle(CustomGraphQLServlet.java:94)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet.doPost(CustomGraphQLServlet.java:77)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.Server.handle(Server.java:501)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at java.lang.Thread.run(Thread.java:748)
```

**Comment by olim7t** [comment]
It might be caused by a JDK bug: https://bugs.openjdk.java.net/browse/JDK-8071667

`computeIfAbsent` is used in `FieldTypeCache.get()` (inherited by `FieldOutputTypeCache`). When a type contains another type (e.g. nested collections, UDTs...), the method recurses into itself to compute sub-types.
