### ISSUE TITLE
Rest Api V2: not able to handle integer in post request

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#49]
```
curl --request POST \
  --url 'localhost:8082/v2/keyspaces/a_manu/widgets' \
 --header 'x-cassandra-token: ef15d2dc-0741-4d58-a499-3ada37788d51'  --header 'accepts: application/json' \
--header 'content-type: application/json' \
--data '{"hour_created":"2020-01-24T11:00:00.00Z","machine_code":"131", "serial_number":"afadfaf","times_inspected":1}' 
{"description":"Server error: java.lang.Integer cannot be cast to java.lang.String","code":500}%
```

start of the stack

```
CREATE TABLE a_manu.widgets (
    hour_created timestamp,
    machine_code text,
    serial_number text,
    created_at timestamp,
    est_unit_cost decimal,
    est_unit_cost_updated timestamp,
    factory_code text,
    inspection_notes text,
    last_inspected_at timestamp,
    part_name text,
    part_number text,
    times_inspected int,
    PRIMARY KEY ((hour_created, machine_code), serial_number)
) WITH CLUSTERING ORDER BY (serial_number ASC)
```

```
ERROR [2020-09-14 14:15:39,471] io.stargate.web.resources.RequestHandler: Error when executing request
! java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
! at io.stargate.web.resources.Converters.colToValue(Converters.java:249)
! at io.stargate.web.resources.v2.RowsResource.lambda$null$2(RowsResource.java:150)
! at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
! at java.util.Iterator.forEachRemaining(Iterator.java:116)
! at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
! at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
! at io.stargate.web.resources.v2.RowsResource.lambda$add$3(RowsResource.java:151)
! at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:24)
! at io.stargate.web.resources.v2.RowsResource.add(RowsResource.java:141)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
```

There is a hack workaround for this, you can just send the integer as a string and it will work, but this will trip a lot of folks up.

**Comment by dougwettlaufer** [comment]
Everything should be sent as a string. We'll have to make sure we cover this in docs.
