### ISSUE TITLE
Persistence bundle startup failure does not cause Stargate process failure

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#591]
Currently if a persistence bundle fails to start with an exception, the overall Stargate process remains running (see below for a DSE example).

Since persistence is a fundamental service of Stargate, it does not make sense to keep the process running as it will not be usable and will not re-attempt connecting to the persistence backend in this state.

```
ERROR [DSE main thread] 2021-01-12 14:34:34,314 CassandraDaemon.java:821 - Exception encountered during startup
java.lang.RuntimeException: A node with address /127.0.2.1 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:786)
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:1157)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:918)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:852)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:419)
	at org.apache.cassandra.service.CassandraDaemon.activate0(CassandraDaemon.java:754)
	at org.apache.cassandra.service.CassandraDaemon.access$100(CassandraDaemon.java:88)
	at org.apache.cassandra.service.CassandraDaemon$3.run(CassandraDaemon.java:715)
java.lang.RuntimeException: A node with address /127.0.2.1 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:786)
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:1157)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:918)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:852)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:419)
	at org.apache.cassandra.service.CassandraDaemon.activate0(CassandraDaemon.java:754)
	at org.apache.cassandra.service.CassandraDaemon.access$100(CassandraDaemon.java:88)
	at org.apache.cassandra.service.CassandraDaemon$3.run(CassandraDaemon.java:715)
ERROR: Bundle io.stargate.db.dse [1] EventDispatcher: Error during dispatch. (java.lang.RuntimeException: Unable to start DSE persistence layer)
java.lang.RuntimeException: Unable to start DSE persistence layer
	at io.stargate.db.dse.impl.DsePersistence.initializePersistence(DsePersistence.java:188)
	at io.stargate.db.dse.impl.DsePersistence.initializePersistence(DsePersistence.java:85)
	at io.stargate.db.datastore.common.AbstractCassandraPersistence.initialize(AbstractCassandraPersistence.java:106)
	at io.stargate.db.dse.DsePersistenceActivator.createService(DsePersistenceActivator.java:142)
	at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:187)
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:123)
	at io.stargate.core.activator.BaseActivator.access$700(BaseActivator.java:34)
	at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:174)
	at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:150)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:128)
	at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:67)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at io.stargate.starter.Starter.start(Starter.java:426)
	at io.stargate.starter.Starter.cli(Starter.java:597)
	at io.stargate.starter.Starter.main(Starter.java:638)
Caused by: java.lang.RuntimeException: Exception encountered during startup
	at org.apache.cassandra.service.CassandraDaemon.exitOrFail(CassandraDaemon.java:927)
	at org.apache.cassandra.service.CassandraDaemon.activate0(CassandraDaemon.java:824)
	at org.apache.cassandra.service.CassandraDaemon.access$100(CassandraDaemon.java:88)
	at org.apache.cassandra.service.CassandraDaemon$3.run(CassandraDaemon.java:715)
Caused by: java.lang.RuntimeException: A node with address /127.0.2.1 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:786)
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:1157)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:918)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:852)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:419)
	at org.apache.cassandra.service.CassandraDaemon.activate0(CassandraDaemon.java:754)
	... 2 more
INFO  [main] 2021-01-12 14:37:48,468 BaseActivator.java:126 - Registering core services as com.codahale.metrics.health.HealthCheckRegistry
INFO  [main] 2021-01-12 14:37:48,468 BaseActivator.java:132 - Started core services
Starting bundle io.stargate.cql
INFO  [main] 2021-01-12 14:37:48,797 BaseActivator.java:64 - Starting CQL ...
Starting bundle io.stargate.graphql
INFO  [main] 2021-01-12 14:37:48,973 BaseActivator.java:64 - Starting GraphQL ...
Starting bundle io.stargate.health
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundle://a49c8615-71bc-4346-8a36-8b7890b6c76a_20.0:82/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundle://a49c8615-71bc-4346-8a36-8b7890b6c76a_20.0:100/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
INFO  [main] 2021-01-12 14:37:49,161 BaseActivator.java:64 - Starting healthchecker ...
INFO  [main] 2021-01-12 14:37:49,162 HealthCheckerActivator.java:30 - Starting healthchecker....
INFO  [2021-01-12 19:37:49,929] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /checker/
WARN  [2021-01-12 19:37:49,929] org.eclipse.jetty.server.handler.ContextHandler: i.d.j.MutableServletContextHandler@508b4f70{/,null,UNAVAILABLE} contextPath ends with /
INFO  [2021-01-12 19:37:49,931] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-01-12 19:37:49,937] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /checker/
WARN  [2021-01-12 19:37:49,937] org.eclipse.jetty.server.handler.ContextHandler: i.d.j.MutableServletContextHandler@508b4f70{/checker,null,UNAVAILABLE} contextPath ends with /
INFO  [2021-01-12 19:37:49,937] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-01-12 19:37:49,937] io.dropwizard.server.ServerFactory: Starting Server
INFO  [2021-01-12 19:37:50,011] org.eclipse.jetty.setuid.SetUIDListener: Opened Server@7e43b342{HTTP/1.1, (http/1.1)}{127.0.2.1:8084}
INFO  [2021-01-12 19:37:50,013] org.eclipse.jetty.server.Server: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 1.8.0_172-b11
INFO  [2021-01-12 19:37:50,429] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /liveness (io.stargate.health.CheckerResource)
    GET     /readiness (io.stargate.health.CheckerResource)

INFO  [2021-01-12 19:37:50,430] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@508b4f70{/checker,null,AVAILABLE}
INFO  [2021-01-12 19:37:50,432] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

WARN  [2021-01-12 19:37:50,432] io.dropwizard.setup.AdminEnvironment: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INFO  [2021-01-12 19:37:50,437] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@238280df{/,null,AVAILABLE}
INFO  [2021-01-12 19:37:50,449] org.eclipse.jetty.server.AbstractConnector: Started Server@7e43b342{HTTP/1.1, (http/1.1)}{127.0.2.1:8084}
INFO  [2021-01-12 19:37:50,449] org.eclipse.jetty.server.Server: Started @207953ms
INFO  [2021-01-12 19:37:50,449] io.stargate.health.HealthCheckerActivator: Started healthchecker....
INFO  [main] 2021-01-12 14:37:50,449 BaseActivator.java:132 - Started healthchecker
Starting bundle org.apache.felix.scr
Starting bundle null
Starting bundle null
Starting bundle osgi.cmpn
Starting bundle org.osgi.util.function
Starting bundle org.osgi.util.promise
Starting bundle io.stargate.db
INFO  [main] 2021-01-12 14:37:50,474 BaseActivator.java:64 - Starting DB services ...
Starting bundle io.stargate.web
INFO  [main] 2021-01-12 14:37:50,687 BaseActivator.java:64 - Starting restapi ...
Finished starting bundles.
```

**Comment by dimas-b** [comment]
Related issue: #587
