### ISSUE TITLE
Stargate isn't able to load schema if Solr is used on a table

### ISSUE THREAD

**Issue by akonchyts** [stargate/stargate#606]
When trying to connect Stargate to the existing DSE 6.8.6 cluster there are errors

`
ERROR [MigrationStage:1] 2021-01-19 10:11:59,814 PullRequestScheduler.java:245 - Configuration exception merging remote schema
org.apache.cassandra.exceptions.ConfigurationException: Unable to find custom indexer class 'com.datastax.bdp.search.solr.Cql3SolrSecondaryIndex'
    at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:493)
    at org.apache.cassandra.schema.IndexMetadata.getCustomIndexClass(IndexMetadata.java:190)
    ....
    at org.apache.cassandra.utils.concurrent.InlinedThreadLocalThread.run(InlinedThreadLocalThread.java:251)
Caused by: java.lang.ClassNotFoundException: com.datastax.bdp.search.solr.Cql3SolrSecondaryIndex not found by io.stargate.db.dse [1]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
    ... 24 common frames omitted
`

This prevents all existing tables (except of some dse system keyspaces) being worked with completely via Stargate using GraphQL, Rest API, cqlsh as Stargate cannot load the schemas if there are tables with Solr used.

**Comment by nvtd4000** [comment]
I see the same problem. After that, I dropped the index but still seeing the same problem. Anyway that I can fix it?
