### ISSUE TITLE
"__conversionWarnings" violates graphQL introspection naming schema

### ISSUE THREAD

**Issue by rongo89** [stargate/stargate#615]
Referring to this change
https://github.com/stargate/stargate/pull/354#issue-512621029

when using codegen in javascript to generate code, based on schema returned by stargate, it results in an error. See below.

```
Error: Name "__conversionWarnings" must not begin with "__", which is reserved by GraphQL introspection.
        at assertValidSchema (/<path>/node_modules/graphql/type/validate.js:69:11)
        at Object.validate (/<path>/node_modules/graphql/validation/validate.js:51:35)
        at /<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:494:32
        at Array.map (<anonymous>)
        at Object.validateGraphQlDocuments (/<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/util
s/index.cjs.js:480:37)
        at Object.codegen (/<path>/node_modules/@graphql-codegen/core/index.cjs.js:95:36)
        at process (/<path>/node_modules/@graphql-codegen/cli/bin.js:940:67)
        at Array.map (<anonymous>)
        at /<path>/node_modules/@graphql-codegen/cli/bin.js:947:63
        at async Task.task (/<path>/node_modules/@graphql-codegen/cli/bin.js:725:17)
    Error: Name "__conversionWarnings" must not begin with "__", which is reserved by GraphQL introspection.
        at assertValidSchema (/<path>/node_modules/graphql/type/validate.js:69:11)
        at Object.validate (/<path>/node_modules/graphql/validation/validate.js:51:35)
        at /<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:494:32
        at Array.map (<anonymous>)
        at Object.validateGraphQlDocuments (/<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/util
s/index.cjs.js:480:37)
        at Object.codegen (/<path>/node_modules/@graphql-codegen/core/index.cjs.js:95:36)
        at process (/<path>/node_modules/@graphql-codegen/cli/bin.js:940:67)
        at Array.map (<anonymous>)
        at /<path>/node_modules/@graphql-codegen/cli/bin.js:947:63
        at async Task.task (/<path>/node_modules/@graphql-codegen/cli/bin.js:725:17)

  ✖ src/graphql/generated/graphql.tsx
    Error: Name "__conversionWarnings" must not begin with "__", which is reserved by GraphQL introspection.
        at assertValidSchema (/<path>/node_modules/graphql/type/validate.js:69:11)
        at Object.validate (/<path>/node_modules/graphql/validation/validate.js:51:35)
        at /<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:494:32
        at Array.map (<anonymous>)
        at Object.validateGraphQlDocuments (/<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/util
s/index.cjs.js:480:37)
        at Object.codegen (/<path>/node_modules/@graphql-codegen/core/index.cjs.js:95:36)
        at process (/<path>/node_modules/@graphql-codegen/cli/bin.js:940:67)
        at Array.map (<anonymous>)
        at /<path>/node_modules/@graphql-codegen/cli/bin.js:947:63
        at async Task.task (/<path>/node_modules/@graphql-codegen/cli/bin.js:725:17)
    Error: Name "__conversionWarnings" must not begin with "__", which is reserved by GraphQL introspection.
        at assertValidSchema (/<path>/node_modules/graphql/type/validate.js:69:11)
        at Object.validate (/<path>/node_modules/graphql/validation/validate.js:51:35)
        at /<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:494:32
        at Array.map (<anonymous>)
        at Object.validateGraphQlDocuments (/<path>/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/util
s/index.cjs.js:480:37)
        at Object.codegen (/<path>/node_modules/@graphql-codegen/core/index.cjs.js:95:36)
        at process (/<path>/node_modules/@graphql-codegen/cli/bin.js:940:67)
        at Array.map (<anonymous>)
        at /<path>/node_modules/@graphql-codegen/cli/bin.js:947:63
        at async Task.task (/<path>/node_modules/@graphql-codegen/cli/bin.js:725:17)
```

**Comment by dougwettlaufer** [comment]
Hi @rongo89 thanks for bringing this up. Does this error completely break your code or does it complain but still work? Can you please tell us a little more about the library you're using? An example to reproduce would be helpful and much appreciated.

cc @olim7t

**Comment by olim7t** [comment]
Indeed, this was an oversight. I'm not sure how lenient client libraries can be, but this is a violation of the spec anyway, it has to be fixed.

The idea was to avoid a collision in the unlikely occurrence that a table has the same name. I can make it a reserved keyword instead (i.e. the table would be escaped).

**Comment by rongo89** [comment]
Hello @dougwettlaufer thanks for picking this up. We are using it in an nextjs project and simply want to run `graphql-codegen --config codegen.yml` to get some code for apollo client. The schema is supposed to be fetched from datastax graphql API, which is based on stargate. The [generator](https://graphql-code-generator.com/) uses the native graphql library

**Comment by paulm17** [comment]
Sorry for the noise.

I'm trying to run codegen with urql.

schema:
  - "http://localhost:8080/graphql/[keyspace]":
    headers:
      x-cassandra-token: ${API_TOKEN}

 I keep getting the following:
 
 ```
 Something went wrong Failed to load schema for "src/generated/index.tsx"
        Failed to load schema from http://localhost:8080/graphql/[keyspace],headers:

        Cannot read properties of null (reading 'loader')
        TypeError: Cannot read properties of null (reading 'loader')
 ```

I've tried the 3 different endpoints, admin, schema and keyspace.

Any help appreciated, thanks!
