### ISSUE TITLE
ERROR: Bundle io.stargate.db.cassandra EventDispatcher: Error during dispatch.

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#678]
I appreciate any help figuring out why I can't get stargate to start. I'm running on CentOS 7.7 with cassandra 3.11.8, and running into issues starting stargate 1.0.7. When I run starctl, I get the following:<br>
<pre><code>
$ ./starctl \
> --cluster-name LR_Cass \
> --cluster-seed 127.0.0.1 \
> --cluster-version 3.11 \
> --listen 127.0.0.2 \
> --dc datacenter1 \
> --rack rack1 \
> --enable-auth
Running java -server -Dstargate.libdir=./stargate-lib -Djava.awt.headless=true -jar ./stargate-lib/stargate-starter-1.0.7.jar --cluster-name LR_Cass --cluster-seed 127.0.0.1 --cluster-version 3.11 --listen 127.0.0.2 --dc datacenter1 --rack rack1 --enable-auth
JAR DIR: ./stargate-lib
Loading persistence backend persistence-cassandra-3.11-1.0.7.jar
Installing bundle persistence-cassandra-3.11-1.0.7.jar
Installing bundle animal-sniffer-annotations-1.9.jar
Installing bundle asm-7.1.jar
Installing bundle asm-analysis-7.1.jar
Installing bundle asm-tree-7.1.jar
Installing bundle auth-api-1.0.7.jar
Installing bundle auth-jwt-service-1.0.7.jar
Installing bundle auth-table-based-service-1.0.7.jar
Installing bundle authnz-1.0.7.jar
Installing bundle commons-beanutils-1.9.4.jar
Installing bundle commons-collections-3.2.2.jar
Installing bundle commons-digester-2.1.jar
Installing bundle commons-logging-1.2.jar
Installing bundle commons-validator-1.7.jar
Installing bundle config-store-api-1.0.7.jar
Installing bundle config-store-yaml-1.0.7.jar
Installing bundle core-1.0.7.jar
Installing bundle cql-1.0.7.jar
Installing bundle graphqlapi-1.0.7.jar
Installing bundle health-checker-1.0.7.jar
Installing bundle org.apache.felix.scr-2.1.20.jar
Installing bundle org.apache.felix.scr.ds-annotations-1.2.10.jar
Installing bundle org.apache.felix.scr.generator-1.18.4.jar
Installing bundle org.osgi.compendium-4.2.0.jar
Installing bundle org.osgi.util.function-1.1.0.jar
Installing bundle org.osgi.util.promise-1.1.1.jar
Installing bundle persistence-api-1.0.7.jar
Installing bundle rate-limiting-global-1.0.7.jar
Installing bundle restapi-1.0.7.jar
Starting bundle io.stargate.db.cassandra
INFO  [main] 2021-02-12 15:28:24,064 BaseActivator.java:92 - Starting persistence-cassandra-3.11 ...
Starting bundle null
Starting bundle org.objectweb.asm
Starting bundle org.objectweb.asm.tree.analysis
Starting bundle org.objectweb.asm.tree
Starting bundle io.stargate.auth.api
INFO  [main] 2021-02-12 15:28:24,233 BaseActivator.java:92 - Starting authApiServer ...
Starting bundle io.stargate.auth.jwt
Starting bundle io.stargate.auth.table
INFO  [main] 2021-02-12 15:28:24,485 BaseActivator.java:92 - Starting authnTableBasedService and authzTableBasedServie ...
Starting bundle io.stargate.auth
Starting bundle org.apache.commons.commons-beanutils
Starting bundle org.apache.commons.collections
Starting bundle org.apache.commons.digester
Starting bundle org.apache.commons.logging
Starting bundle org.apache.commons.commons-validator
Starting bundle io.stargate.config.store.api
Starting bundle io.stargate.config.store.yaml
INFO  [main] 2021-02-12 15:28:24,588 BaseActivator.java:92 - Starting Config Store YAML ...
Starting bundle io.stargate.core
INFO  [main] 2021-02-12 15:28:24,589 BaseActivator.java:92 - Starting core services ...
INFO  [main] 2021-02-12 15:28:24,591 BaseActivator.java:173 - Registering core services as io.stargate.core.metrics.api.Metrics
INFO  [main] 2021-02-12 15:28:24,635 ConfigStoreActivator.java:57 - Creating Config Store YAML for config file location: /etc/stargate/stargate-config.yaml
INFO  [main] 2021-02-12 15:28:24,777 BaseActivator.java:173 - Registering Config Store YAML as io.stargate.config.store.api.ConfigStore
INFO  [main] 2021-02-12 15:28:24,777 BaseActivator.java:180 - Started Config Store YAML
INFO  [main] 2021-02-12 15:28:24,921 AbstractCassandraPersistence.java:100 - Initializing Apache Cassandra
INFO  [main] 2021-02-12 15:28:24,948 DatabaseDescriptor.java:381 - DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
INFO  [main] 2021-02-12 15:28:24,949 DatabaseDescriptor.java:439 - Global memtable on-heap threshold is enabled at 434MB
INFO  [main] 2021-02-12 15:28:24,949 DatabaseDescriptor.java:443 - Global memtable off-heap threshold is enabled at 434MB
WARN  [main] 2021-02-12 15:28:24,951 DatabaseDescriptor.java:503 - Small commitlog volume detected at /tmp/stargate-cassandra-3.118317113922203938675/commitlog; setting commitlog_total_space_in_mb to 5007.  You can override this in cassandra.yaml
WARN  [main] 2021-02-12 15:28:24,952 DatabaseDescriptor.java:530 - Small cdc volume detected at /tmp/stargate-cassandra-3.118317113922203938675/cdc; setting cdc_total_space_in_mb to 2503.  You can override this in cassandra.yaml
WARN  [main] 2021-02-12 15:28:25,028 DatabaseDescriptor.java:579 - Only 15.521GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
INFO  [main] 2021-02-12 15:28:25,048 RateBasedBackPressure.java:123 - Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 2000.
INFO  [main] 2021-02-12 15:28:25,048 DatabaseDescriptor.java:773 - Back-pressure is disabled with strategy null.
INFO  [main] 2021-02-12 15:28:25,064 GossipingPropertyFileSnitch.java:68 - Unable to load cassandra-topology.properties; compatibility mode disabled
ERROR: Bundle io.stargate.db.cassandra [1] EventDispatcher: Error during dispatch. (io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11)
io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:182)
	at io.stargate.core.activator.BaseActivator.access$900(BaseActivator.java:37)
	at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:225)
	at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:201)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:175)
	at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:98)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at io.stargate.starter.Starter.start(Starter.java:431)
	at io.stargate.starter.Starter.cli(Starter.java:607)
	at io.stargate.starter.Starter.main(Starter.java:648)
Caused by: java.lang.RuntimeException: Port already in use: 7199; nested exception is:
	java.net.BindException: Address already in use (Bind failed)
	at org.apache.cassandra.service.CassandraDaemon.exitOrFail(CassandraDaemon.java:769)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:156)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:195)
	at org.apache.cassandra.service.CassandraDaemon.init(CassandraDaemon.java:521)
	at io.stargate.db.cassandra.impl.CassandraPersistence.initializePersistence(CassandraPersistence.java:171)
	at io.stargate.db.cassandra.impl.CassandraPersistence.initializePersistence(CassandraPersistence.java:94)
	at io.stargate.db.datastore.common.AbstractCassandraPersistence.initialize(AbstractCassandraPersistence.java:106)
	at io.stargate.db.cassandra.CassandraPersistenceActivator.createService(CassandraPersistenceActivator.java:169)
	at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:238)
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:170)
	... 25 more
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:390)
	at java.net.ServerSocket.<init>(ServerSocket.java:252)
	at java.net.ServerSocket.<init>(ServerSocket.java:143)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createServerSocket(RMIDirectSocketFactory.java:45)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createServerSocket(RMIMasterSocketFactory.java:345)
	at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:237)
	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:173)
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:144)
	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:239)
	at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:75)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:150)
	... 33 more
INFO  [main] 2021-02-12 15:28:25,109 BaseActivator.java:173 - Registering core services as com.codahale.metrics.health.HealthCheckRegistry
Detected service startup failure in bundle io.stargate.db.cassandra: io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
io.stargate.core.activator.ServiceStartException: Unable to start persistence-cassandra-3.11
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:182)
	at io.stargate.core.activator.BaseActivator.access$900(BaseActivator.java:37)
	at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:225)
INFO  [main] 2021-02-12 15:28:25,109 BaseActivator.java:180 - Started core services
	at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:201)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)Starting bundle io.stargate.cql

```
at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:175)
at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:98)
at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
at io.stargate.starter.Starter.start(Starter.java:431)
at io.stargate.starter.Starter.cli(Starter.java:607)
at io.stargate.starter.Starter.main(Starter.java:648)
```

Caused by: java.lang.RuntimeException: Port already in use: 7199; nested exception is:
	java.net.BindException: Address already in use (Bind failed)
	at org.apache.cassandra.service.CassandraDaemon.exitOrFail(CassandraDaemon.java:769)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:156)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:195)
	at org.apache.cassandra.service.CassandraDaemon.init(CassandraDaemon.java:521)
	at io.stargate.db.cassandra.impl.CassandraPersistence.initializePersistence(CassandraPersistence.java:171)
	at io.stargate.db.cassandra.impl.CassandraPersistence.initializePersistence(CassandraPersistence.java:94)
	at io.stargate.db.datastore.common.AbstractCassandraPersistence.initialize(AbstractCassandraPersistence.java:106)
	at io.stargate.db.cassandra.CassandraPersistenceActivator.createService(CassandraPersistenceActivator.java:169)
	at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:238)
	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:170)
	... 25 more
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:390)
	at java.net.ServerSocket.<init>(ServerSocket.java:252)
	at java.net.ServerSocket.<init>(ServerSocket.java:143)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createServerSocket(RMIDirectSocketFactory.java:45)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createServerSocket(RMIMasterSocketFactory.java:345)
	at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:237)
	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:173)
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:144)
	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:239)
	at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:75)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:150)
	... 33 more
INFO  [main] 2021-02-12 15:28:25,379 BaseActivator.java:92 - Starting CQL ...
Starting bundle io.stargate.graphql
INFO  [main] 2021-02-12 15:28:25,548 BaseActivator.java:92 - Starting GraphQL ...
Starting bundle io.stargate.health
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundle://61f83ad1-1a3b-4976-8c43-07a65aa4c773_20.0:82/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundle://61f83ad1-1a3b-4976-8c43-07a65aa4c773_20.0:100/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
INFO  [main] 2021-02-12 15:28:25,738 BaseActivator.java:92 - Starting healthchecker ...
INFO  [main] 2021-02-12 15:28:25,740 HealthCheckerActivator.java:37 - Starting healthchecker....
INFO  [2021-02-12 22:28:26,554] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /checker/
WARN  [2021-02-12 22:28:26,554] org.eclipse.jetty.server.handler.ContextHandler: i.d.j.MutableServletContextHandler@67d4c48d{/,null,UNAVAILABLE} contextPath ends with /
INFO  [2021-02-12 22:28:26,555] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-02-12 22:28:26,561] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /checker/
WARN  [2021-02-12 22:28:26,561] org.eclipse.jetty.server.handler.ContextHandler: i.d.j.MutableServletContextHandler@67d4c48d{/checker,null,UNAVAILABLE} contextPath ends with /
INFO  [2021-02-12 22:28:26,561] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-02-12 22:28:26,561] io.dropwizard.server.ServerFactory: Starting Server
INFO  [2021-02-12 22:28:26,638] org.eclipse.jetty.setuid.SetUIDListener: Opened Server@1a531422{HTTP/1.1, (http/1.1)}{0.0.0.0:8084}
INFO  [2021-02-12 22:28:26,639] org.eclipse.jetty.server.Server: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 1.8.0_242-b08
INFO  [2021-02-12 22:28:27,135] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

```
GET     /liveness (io.stargate.health.CheckerResource)
GET     /readiness (io.stargate.health.CheckerResource)
```

INFO  [2021-02-12 22:28:27,137] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@67d4c48d{/checker,null,AVAILABLE}
INFO  [2021-02-12 22:28:27,140] io.dropwizard.setup.AdminEnvironment: tasks =

```
POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)
```

INFO  [2021-02-12 22:28:27,144] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@74c9e11{/,null,AVAILABLE}
INFO  [2021-02-12 22:28:27,151] org.eclipse.jetty.server.AbstractConnector: Started Server@1a531422{HTTP/1.1, (http/1.1)}{0.0.0.0:8084}
INFO  [2021-02-12 22:28:27,152] org.eclipse.jetty.server.Server: Started 4097ms
INFO  [main] 2021-02-12 15:28:27,152 BaseActivator.java:180 - Started healthchecker
Starting bundle org.apache.felix.scr
INFO  [2021-02-12 22:28:27,152] io.stargate.health.HealthCheckerActivator: Started healthchecker....
Starting bundle null
Starting bundle null
Starting bundle osgi.cmpn
Starting bundle org.osgi.util.function
Starting bundle org.osgi.util.promise
Starting bundle io.stargate.db
INFO  [main] 2021-02-12 15:28:27,174 BaseActivator.java:92 - Starting DB services ...
Starting bundle io.stargate.db.limiter.global
INFO  [main] 2021-02-12 15:28:27,177 BaseActivator.java:92 - Starting Global Rate Limiting ...
INFO  [main] 2021-02-12 15:28:27,178 BaseActivator.java:180 - Started Global Rate Limiting
Starting bundle io.stargate.web
INFO  [main] 2021-02-12 15:28:27,343 BaseActivator.java:92 - Starting restapi ...
Terminating due to previous service startup errors.
INFO  [2021-02-12 22:28:27,354] org.eclipse.jetty.server.AbstractConnector: Stopped Server@1a531422{HTTP/1.1, (http/1.1)}{0.0.0.0:8084}
INFO  [2021-02-12 22:28:27,356] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@74c9e11{/,null,UNAVAILABLE}
INFO  [2021-02-12 22:28:27,361] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@67d4c48d{/checker,null,UNAVAILABLE}`
</code></pre>

Here is the output from nodetool status and info:<br>
<pre><code>
$ ./apache-cassandra-3.11.8/bin/nodetool status

# Datacenter: datacenter1
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  127.0.0.1  240.54 KiB  256          100.0%            05ae24fd-e340-44c6-8acf-302053740267  rack1

$ ./apache-cassandra-3.11.8/bin/nodetool info
ID                     : 05ae24fd-e340-44c6-8acf-302053740267
Gossip active          : true
Thrift active          : true
Native Transport active: true
Load                   : 240.54 KiB
Generation No          : 1613154334
Uptime (seconds)       : 14503
Heap Memory (MB)       : 112.81 / 1936.00
Off Heap Memory (MB)   : 0.00
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 13, size 1.05 KiB, capacity 96 MiB, 71 hits, 88 requests, 0.807 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 48 MiB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Chunk Cache            : entries 10, size 640 KiB, capacity 452 MiB, 39 misses, 136 requests, 0.713 recent hit rate, NaN microseconds miss latency
Percent Repaired       : 100.0%
Token                  : (invoke with -T/--tokens to see all 256 tokens)
</code></pre>

**Comment by dougwettlaufer** [comment]
Hi @john-gress. Do you have jmx enabled on your C* cluster? By default stargate is going to listen on 7199. Here's what my localhost looks like running stargate and a single C* node

```shell
lsof -nP -iTCP | grep LISTEN | grep java | awk '{print $1, $2, $5, $9}'                                                                                                                                                                                                                                                                                          java 2041 IPv6 *:7199
java 2041 IPv6 *:58811
java 2041 IPv6 127.0.0.2:7000
java 2041 IPv6 *:8081
java 2041 IPv6 *:8084
java 2041 IPv6 *:9042
java 2041 IPv6 *:8080
java 2041 IPv6 *:8082
java 85927 IPv4 127.0.0.1:7100
java 85927 IPv4 127.0.0.1:58680
java 85927 IPv4 127.0.0.1:7000
java 85927 IPv4 127.0.0.1:9042
java 85927 IPv4 127.0.0.1:9160
java 92922 IPv6 127.0.0.1:51828
java 92922 IPv6 127.0.0.1:57410
```

You can avoid this collision by changing the jmx port in stargate with `--jmx-port 7299`.

**Comment by john-gress** [comment]
Hi @dougwettlaufer,

Thanks for your help!

The `--jmx-port 7299` gets me past the error. Then I discovered I needed to also change the cql port (`--cql-port 9142`) because I had a collision there too.

Here's the output from lsof, before starting stargate:
<pre><code>
java 2818 IPv4 127.0.0.1:7199
java 2818 IPv4 127.0.0.1:46080
java 2818 IPv4 127.0.0.1:7000
java 2818 IPv4 127.0.0.1:9042
</code></pre>

Process 2818 corresponds to my C* cluster. So when using stargate is it recommended I disable jmx and cql?

**Comment by dougwettlaufer** [comment]
These sort of collisions will only happen when stargate and C* run on the same host so primarily an issue for local testing. Your options are to either change the ports like you found or change the jmx port and set `--bind-to-listen-address` which will cause stargate to bind to `127.0.0.2:9042` rather than `*:9042`.

**Comment by john-gress** [comment]
Thanks again @dougwettlaufer! This has been very helpful.

**Comment by dougwettlaufer** [comment]
Great! You're welcome @john-gress
