### ISSUE TITLE
Integration tests fail to run on mac

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#702]
When running the integration tests on mac from IntelliJ the following error occurs

```

INFO  [main] 2021-02-19 23:43:07,891 ExternalStorage.java:105 - Creating storage cluster @io.stargate.it.storage.ClusterSpec(shared=true, nodes=1) for [engine:junit-jupiter]/[class:io.stargate.it.http.RestApiv2Test]
INFO  [main] 2021-02-19 23:43:09,869 ProcessRunner.java:101 - Starting Storage 0, node 0: [/var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/bin/cassandra, -f, -Dcassandra.logdir=/var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/logs, -Dcassandra.boot_without_jna=true]
INFO  [main] 2021-02-19 23:43:09,871 ProcessRunner.java:105 - Started Storage 0, node 0: [/var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/bin/cassandra, -f, -Dcassandra.logdir=/var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/logs, -Dcassandra.boot_without_jna=true]
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,257 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 34: sysctl: command not found
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,271 ProcessRunner.java:83 - storage0-0> expr: syntax error
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,273 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 36: sysctl: command not found
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,277 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 47: [: : integer expression expected
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,282 ProcessRunner.java:83 - storage0-0> expr: syntax error
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,291 ProcessRunner.java:83 - storage0-0> expr: syntax error
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,291 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 59: [: : integer expression expected
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,292 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 63: [: : integer expression expected
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,292 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 67: [: : integer expression expected
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,296 ProcessRunner.java:83 - storage0-0> expr: syntax error
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,301 ProcessRunner.java:83 - storage0-0> expr: syntax error
ERROR [Exec Stream Pumper] 2021-02-19 23:43:10,302 ProcessRunner.java:83 - storage0-0> /var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/conf/cassandra-env.sh: line 81: [: : integer expression expected
ERROR [Exec Stream Pumper] 2021-02-19 23:43:11,522 ProcessRunner.java:83 - storage0-0> intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
INFO  [Exec Stream Pumper] 2021-02-19 23:43:11,522 ProcessRunner.java:76 - storage0-0> [0.005s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/var/folders/t8/b8xsyd7x49vcw530y76g8t4w0000gn/T/ccm1807638996416850746/ccm_1/node1/logs/gc.log instead.
ERROR [Exec Stream Pumper] 2021-02-19 23:43:11,522 ProcessRunner.java:83 - storage0-0> Improperly specified VM option 'ThreadPriorityPolicy=42'
ERROR [Exec Stream Pumper] 2021-02-19 23:43:11,523 ProcessRunner.java:83 - storage0-0> Error: Could not create the Java Virtual Machine.
ERROR [Exec Stream Pumper] 2021-02-19 23:43:11,523 ProcessRunner.java:83 - storage0-0> Error: A fatal exception has occurred. Program will exit.
INFO  [process-runner-storage-0-0] 2021-02-19 23:43:11,526 ProcessRunner.java:157 - Storage process 0/0 failed with exception: {}
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:748)

Test ignored.
```

**Comment by dimas-b** [comment]
Is that across all storage versions, or some specific C*/DSE version?

**Comment by dougwettlaufer** [comment]
This was specifically to C* 3.11 but is probably present across all of them.

**Comment by dimas-b** [comment]
Hmmm, this used to work on Mac when we switched to `ccm`, right? What version of `ccm` do you use?

**Comment by olim7t** [comment]
It stopped working for me too, without any changes to CCM. It works on a commit from about 4 weeks ago. I'll try to do a bisect.

**Comment by olim7t** [comment]
Introduced by #640.
