### ISSUE TITLE
Querying GraphQL API with `limit` fails

### ISSUE THREAD

**Issue by marksurnin** [stargate/stargate#716]
I have a simple table with a handful of rows

```
CREATE TABLE test.user (
    id int PRIMARY KEY,
    name text
) WITH ...
```

and I get an `Exception while fetching data (/user) : org.apache.cassandra.stargate.exceptions.InvalidRequestException: Expected 4 or 0 byte int (8)` when I run this query

```
{
  user(options: {limit: 2}) {
    values{
      id
    }
  }
}
```

The query works fine if I pass another query option such as `pageSize`. The exception originates in [Int32Serializer](https://github.com/apache/cassandra/blob/cassandra-3.11.6/src/java/org/apache/cassandra/serializers/Int32Serializer.java#L42) as this is the serializer that's used for `LIMIT`. Could this be related to `limit` being parsed and converted to a Long in [QueryBuilderImpl](https://github.com/stargate/stargate/blob/master/persistence-api/src/main/java/io/stargate/db/query/builder/QueryBuilderImpl.java#L146) and [BuiltSelect](https://github.com/stargate/stargate/blob/master/persistence-api/src/main/java/io/stargate/db/query/builder/BuiltSelect.java#L34)?

Here's the full stack trace for reference:

```
WARN  [2021-02-26 11:38:39,376] notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler: Exception while fetching data (/user) : org.apache.cassandra.stargate.exceptions.InvalidRequestException: Expected 4 or 0 byte int (8)
! org.apache.cassandra.stargate.exceptions.InvalidRequestException: Expected 4 or 0 byte int (8)
! at io.stargate.db.cassandra.impl.Conversion.toExternal(Conversion.java:340)
! at io.stargate.db.cassandra.impl.Conversion.convertInternalException(Conversion.java:472)
! at io.stargate.db.cassandra.impl.CassandraPersistence$CassandraConnection.lambda$executeRequestOnExecutor$0(CassandraPersistence.java:396)
! at io.stargate.db.cassandra.impl.CassandraPersistence.lambda$runOnExecutor$1(CassandraPersistence.java:247)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165)
! at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:137)
! at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)
! ... 1 common frames omitted
! Suppressed: org.apache.cassandra.exceptions.InvalidRequestException: Expected 4 or 0 byte int (8)
! 	at org.apache.cassandra.cql3.Constants$Marker.bindAndGet(Constants.java:355)
! 	at org.apache.cassandra.cql3.statements.SelectStatement.getLimit(SelectStatement.java:741)
! 	at org.apache.cassandra.cql3.statements.SelectStatement.getLimit(SelectStatement.java:720)
! 	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:279)
! 	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:117)
! 	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
! 	at org.apache.cassandra.cql3.QueryProcessor.processPrepared(QueryProcessor.java:532)
! 	at org.apache.cassandra.cql3.QueryProcessor.processPrepared(QueryProcessor.java:509)
! 	at io.stargate.db.cassandra.impl.StargateQueryHandler.processPrepared(StargateQueryHandler.java:199)
! 	at org.apache.cassandra.transport.messages.ExecuteMessage.execute(ExecuteMessage.java:146)
! 	at io.stargate.db.cassandra.impl.CassandraPersistence$CassandraConnection.lambda$executeRequestOnExecutor$0(CassandraPersistence.java:389)
! 	... 6 common frames omitted
! Causing: java.util.concurrent.ExecutionException: org.apache.cassandra.stargate.exceptions.InvalidRequestException: Expected 4 or 0 byte int (8)
! at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
! at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
! at io.stargate.graphql.schema.fetchers.dml.QueryFetcher.lambda$get$0(QueryFetcher.java:65)
! at io.stargate.auth.table.AuthzTableBasedService.authorizedDataRead(AuthzTableBasedService.java:46)
! at io.stargate.graphql.schema.fetchers.dml.QueryFetcher.get(QueryFetcher.java:64)
! at io.stargate.graphql.schema.fetchers.dml.QueryFetcher.get(QueryFetcher.java:44)
! at io.stargate.graphql.schema.fetchers.CassandraFetcher.get(CassandraFetcher.java:90)
! at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:272)
! at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:200)
! at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
! at graphql.execution.Execution.executeOperation(Execution.java:165)
! at graphql.execution.Execution.execute(Execution.java:106)
! at graphql.GraphQL.execute(GraphQL.java:623)
! at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556)
! at graphql.GraphQL.executeAsync(GraphQL.java:520)
! at io.stargate.graphql.web.resources.GraphqlResourceBase.executeAsync(GraphqlResourceBase.java:166)
! at io.stargate.graphql.web.resources.GraphqlResourceBase.postJson(GraphqlResourceBase.java:136)
! at io.stargate.graphql.web.resources.GraphqlDmlResource.postJson(GraphqlDmlResource.java:104)
...
```

**Comment by olim7t** [comment]
Hi,
Your guess is spot on, the issue comes from the fact that the query builder tries to bind a long, when the persistence backend expects an int. I'll start working on a fix.

**Comment by marksurnin** [comment]
Thank you!
