### ISSUE TITLE
Starting multiple Stargate nodes with C* 3.11 may experience schema disagreement

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#800]
When starting 2 or more stargate nodes at the same time while using C* 3.11 as the backend there is a potential for schema disagreement which manifests as

```java
ERROR [Native-Transport-Requests-1] 2021-03-25 20:24:03,774 QueryMessage.java:129 - Unexpected error during query
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 0a8bac40-8da8-11eb-b9d6-3784f6de5a75; expected 0a7a9540-8da8-11eb-a6b7-cf8e2a7d4c99)
	at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:443)
	at org.apache.cassandra.service.MigrationManager.announce(MigrationManager.java:572)
	at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:369)
	at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:354)
	at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:349)
	at org.apache.cassandra.cql3.statements.CreateTableStatement.announceMigration(CreateTableStatement.java:89)
	at org.apache.cassandra.cql3.statements.SchemaAlteringStatement.execute(SchemaAlteringStatement.java:123)
	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
	at io.stargate.db.cassandra.impl.StargateQueryHandler.process(StargateQueryHandler.java:160)
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)
	at io.stargate.db.cassandra.impl.CassandraPersistence$CassandraConnection.lambda$executeRequestOnExecutor$0(CassandraPersistence.java:439)
	at io.stargate.db.cassandra.impl.CassandraPersistence.lambda$runOnExecutor$1(CassandraPersistence.java:271)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)
	at java.lang.Thread.run(Thread.java:748)
```

Needs more investigation but at first glance this appears to be related to multiple stargate nodes starting at once and all trying to create the keyspace for table based auth. A potential work around is to start stargate with `-Dstargate.auth_tablebased_init=false` to avoid this issue with concurrent schema changes in 3.11.

**Comment by tub** [comment]
We saw exactly this when we were first deploying against a multi-node 3.11 cluster. `-Dstargate.auth_tablebased_init=false` did indeed prevent the schema disagreements happening.

**Comment by jeffreyscarpenter** [comment]
Workaround exists and C* 3.11 persistence is deprecated. Closing as won't fix.
