### ISSUE TITLE
Flaky integration test: SystemTablesTest.addAndRemovePeers

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#984]
CI logs:

```
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:12,189 ProcessRunner.java:117 - Stargate 1/2 is ready
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:12,189 ProcessRunner.java:78 - stargate1-2> Finished starting bundles.
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:13,198 ProcessRunner.java:122 - Stopping Stargate process 1/2
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:13,198 ProcessRunner.java:124 - Signaled Stargate process 1/2 to stop
Step #4 - "cassandra-3.11": INFO  [process-runner-stargate-1-2] 2021-06-01 17:43:13,714 ProcessRunner.java:154 - Stargate process 1/2 exited with return code 143
Step #4 - "cassandra-3.11": WARN  [s0-admin-0] 2021-06-01 17:43:14,758 Loggers.java:39 - [s0|/127.0.2.4:9043]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.9.0, CLIENT_ID=27426906-0f10-4363-8354-0c6377605bcb}): failed to send request (java.nio.channels.ClosedChannelException))
Step #4 - "cassandra-3.11": WARN  [s0-admin-0] 2021-06-01 17:43:17,062 Loggers.java:39 - [s0|/127.0.2.4:9043]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.9.0, CLIENT_ID=27426906-0f10-4363-8354-0c6377605bcb}): failed to send request (java.nio.channels.ClosedChannelException))
Step #4 - "cassandra-3.11": WARN  [s0-admin-0] 2021-06-01 17:43:21,346 Loggers.java:39 - [s0|/127.0.2.4:9043]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.9.0, CLIENT_ID=27426906-0f10-4363-8354-0c6377605bcb}): failed to send request (java.nio.channels.ClosedChannelException))
Step #4 - "cassandra-3.11": WARN  [s0-admin-0] 2021-06-01 17:43:28,789 Loggers.java:39 - [s0|/127.0.2.4:9043]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.9.0, CLIENT_ID=27426906-0f10-4363-8354-0c6377605bcb}): failed to send request (java.nio.channels.ClosedChannelException))
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:32,386 ProcessRunner.java:78 - storage0-0> INFO  [GossipStage:1] 2021-06-01 17:43:32,386 Gossiper.java:1119 - InetAddress /127.0.2.4 is now DOWN
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:34,281 ProcessRunner.java:78 - stargate1-0> INFO  [GossipStage:1] 2021-06-01 17:43:34,281 Gossiper.java:1119 - InetAddress /127.0.2.4 is now DOWN
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:35,105 ProcessRunner.java:78 - stargate1-1> INFO  [GossipStage:1] 2021-06-01 17:43:35,104 Gossiper.java:1119 - InetAddress /127.0.2.4 is now DOWN
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:43,110 ProcessRunner.java:78 - stargate1-1> INFO  [GossipTasks:1] 2021-06-01 17:43:43,109 Gossiper.java:893 - FatClient /127.0.2.4 has been silent for 30000ms, removing from gossip
Step #4 - "cassandra-3.11": WARN  [s0-admin-0] 2021-06-01 17:43:43,193 Loggers.java:39 - [s0|/127.0.2.4:9043]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.9.0, CLIENT_ID=27426906-0f10-4363-8354-0c6377605bcb}): failed to send request (java.nio.channels.ClosedChannelException))
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:43,392 ProcessRunner.java:78 - storage0-0> INFO  [GossipTasks:1] 2021-06-01 17:43:43,392 Gossiper.java:893 - FatClient /127.0.2.4 has been silent for 30000ms, removing from gossip
Step #4 - "cassandra-3.11": WARN  [main] 2021-06-01 17:43:44,831 ExternalStorage.java:140 - Error in [engine:junit-jupiter]/[class:io.stargate.it.cql.SystemTablesTest]/[method:addAndRemovePeers(com.datastax.oss.driver.api.core.CqlSession, io.stargate.it.storage.StargateEnvironmentInfo)]
Step #4 - "cassandra-3.11": org.opentest4j.AssertionFailedError: 
Step #4 - "cassandra-3.11": Expecting:
Step #4 - "cassandra-3.11":  <com.datastax.oss.driver.internal.core.cql.DefaultRow@4387d2f4>
Step #4 - "cassandra-3.11": to be equal to:
Step #4 - "cassandra-3.11":  <null>
Step #4 - "cassandra-3.11": but was not.
Step #4 - "cassandra-3.11": 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Step #4 - "cassandra-3.11": 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Step #4 - "cassandra-3.11": 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Step #4 - "cassandra-3.11": 	at io.stargate.it.cql.SystemTablesTest.addAndRemovePeers(SystemTablesTest.java:84)
Step #4 - "cassandra-3.11": 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #4 - "cassandra-3.11": 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #4 - "cassandra-3.11": 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #4 - "cassandra-3.11": 	at java.lang.reflect.Method.invoke(Method.java:498)
Step #4 - "cassandra-3.11": 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
Step #4 - "cassandra-3.11": 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
Step #4 - "cassandra-3.11": 	at java.util.ArrayList.forEach(ArrayList.java:1259)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
Step #4 - "cassandra-3.11": 	at java.util.ArrayList.forEach(ArrayList.java:1259)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
Step #4 - "cassandra-3.11": 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
Step #4 - "cassandra-3.11": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
Step #4 - "cassandra-3.11": 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
Step #4 - "cassandra-3.11": 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
Step #4 - "cassandra-3.11": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
Step #4 - "cassandra-3.11": 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
Step #4 - "cassandra-3.11": 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
Step #4 - "cassandra-3.11": 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
Step #4 - "cassandra-3.11": 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
Step #4 - "cassandra-3.11": 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
Step #4 - "cassandra-3.11": 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
Step #4 - "cassandra-3.11": 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:44,839 ProcessRunner.java:78 - stargate1-1> INFO  [Native-Transport-Requests-1] 2021-06-01 17:43:44,838 MigrationManager.java:495 - Drop Keyspace 'ks_1622569366325_SystemTablesTest'
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-06-01 17:43:45,287 ProcessRunner.java:78 - stargate1-0> INFO  [GossipTasks:1] 2021-06-01 17:43:45,286 Gossiper.java:893 - FatClient /127.0.2.4 has been silent for 30000ms, removing from gossip
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:49,240 ExternalResource.java:119 - Closing StargateContainer resource in [engine:junit-jupiter]/[class:io.stargate.it.cql.SystemTablesTest]
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:49,240 ProcessRunner.java:122 - Stopping Stargate process 1/0
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:49,240 ProcessRunner.java:124 - Signaled Stargate process 1/0 to stop
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:49,240 ProcessRunner.java:122 - Stopping Stargate process 1/1
Step #4 - "cassandra-3.11": INFO  [main] 2021-06-01 17:43:49,240 ProcessRunner.java:124 - Signaled Stargate process 1/1 to stop
Step #4 - "cassandra-3.11": INFO  [process-runner-stargate-1-0] 2021-06-01 17:43:49,720 ProcessRunner.java:154 - Stargate process 1/0 exited with return code 143
Step #4 - "cassandra-3.11": INFO  [process-runner-stargate-1-1] 2021-06-01 17:43:49,771 ProcessRunner.java:154 - Stargate process 1/1 exited with return code 143
Step #4 - "cassandra-3.11": [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 98.875 s <<< FAILURE! - in io.stargate.it.cql.SystemTablesTest
Step #4 - "cassandra-3.11": [ERROR] addAndRemovePeers{CqlSession, StargateEnvironmentInfo}  Time elapsed: 55.683 s  <<< FAILURE!
Step #4 - "cassandra-3.11": org.opentest4j.AssertionFailedError: 
Step #4 - "cassandra-3.11": 
Step #4 - "cassandra-3.11": Expecting:
Step #4 - "cassandra-3.11":  <com.datastax.oss.driver.internal.core.cql.DefaultRow@4387d2f4>
Step #4 - "cassandra-3.11": to be equal to:
Step #4 - "cassandra-3.11":  <null>
Step #4 - "cassandra-3.11": but was not.
Step #4 - "cassandra-3.11": 	at io.stargate.it.cql.SystemTablesTest.addAndRemovePeers(SystemTablesTest.java:84)
```

**Comment by ivansenic** [comment]
Have seen the same a while ago.
