### ISSUE TITLE
Failed to open hints directory

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#991]
After running for several weeks we are seeing frequent exceptions (see below) around failing to open the hints directory. It looks like this is a result of CentOS automatically deleting files/directories in /tmp after a period of time.

Is there a recommendation for how to deal with this issue? Can the hints directory be relocated somewhere besides /tmp?

See https://stackoverflow.com/questions/61264024/unable-to-open-hint-directory

Thanks,
John Gress

<pre><code>
2021-06-03 14:08:17,384 [HintsWriteExecutor:1] WARN  o.a.cassandra.utils.NativeLibrary - open(/tmp/stargate-cassandra-3.117232734951422798831/hints, O_RDONLY) failed, errno (2).
2021-06-03 14:08:17,384 [HintsWriteExecutor:1] ERROR o.a.cassandra.hints.HintsCatalog - Unable to open directory /tmp/stargate-cassandra-3.117232734951422798831/hints
2021-06-03 14:08:17,385 [HintsWriteExecutor:1] ERROR o.a.c.service.CassandraDaemon - Exception in thread Thread[HintsWriteExecutor:1,5,main]
org.apache.cassandra.io.FSWriteError: java.io.IOException: Unable to open hint directory /tmp/stargate-cassandra-3.117232734951422798831/hints
	at org.apache.cassandra.hints.HintsCatalog.fsyncDirectory(HintsCatalog.java:168)
	at org.apache.cassandra.hints.HintsWriteExecutor$FsyncWritersTask.run(HintsWriteExecutor.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to open hint directory /tmp/stargate-cassandra-3.117232734951422798831/hints
	... 8 common frames omitted
2021-06-03 14:08:17,385 [BatchlogTasks:1] ERROR o.a.c.service.CassandraDaemon - Exception in thread Thread[BatchlogTasks:1,5,main]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: FSWriteError in /tmp/stargate-cassandra-3.117232734951422798831/hints
	at org.apache.cassandra.hints.HintsWriteExecutor.fsyncWritersBlockingly(HintsWriteExecutor.java:107)
	at org.apache.cassandra.hints.HintsService.flushAndFsyncBlockingly(HintsService.java:191)
	at org.apache.cassandra.batchlog.BatchlogManager.processBatchlogEntries(BatchlogManager.java:281)
	at org.apache.cassandra.batchlog.BatchlogManager.replayFailedBatches(BatchlogManager.java:222)
	at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: FSWriteError in /tmp/stargate-cassandra-3.117232734951422798831/hints
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.cassandra.hints.HintsWriteExecutor.fsyncWritersBlockingly(HintsWriteExecutor.java:103)
	... 12 common frames omitted
Caused by: org.apache.cassandra.io.FSWriteError: java.io.IOException: Unable to open hint directory /tmp/stargate-cassandra-3.117232734951422798831/hints
	at org.apache.cassandra.hints.HintsCatalog.fsyncDirectory(HintsCatalog.java:168)
	at org.apache.cassandra.hints.HintsWriteExecutor$FsyncWritersTask.run(HintsWriteExecutor.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 common frames omitted
Caused by: java.io.IOException: Unable to open hint directory /tmp/stargate-cassandra-3.117232734951422798831/hints
	... 8 common frames omitted
2021-06-03 14:08:17,385 [BatchlogTasks:1] ERROR o.a.c.service.CassandraDaemon - Exception in thread Thread[BatchlogTasks:1,5,main]
org.apache.cassandra.io.FSWriteError: java.io.IOException: Unable to open hint directory /tmp/stargate-cassandra-3.117232734951422798831/hints
	at org.apache.cassandra.hints.HintsCatalog.fsyncDirectory(HintsCatalog.java:168)
	at org.apache.cassandra.hints.HintsWriteExecutor$FsyncWritersTask.run(HintsWriteExecutor.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to open hint directory /tmp/stargate-cassandra-3.117232734951422798831/hints
	... 8 common frames omitted
</code></pre>

**Comment by mpenick** [comment]
> Can the hints directory be relocated somewhere besides /tmp?

Unfortunately not as it's currently implemented:
https://github.com/stargate/stargate/blob/v1.0.25/persistence-cassandra-3.11/src/main/java/io/stargate/db/cassandra/CassandraPersistenceActivator.java#L169

However, we could add a system property to allow the directory to be configurable.

**Comment by john-gress** [comment]
That would be helpful. When can we expect the change to be available?

**Comment by mpenick** [comment]
@john-gress Hi, I added a PR for this: https://github.com/stargate/stargate/pull/993. I still need to add some test. Let me know what you think.

**Comment by john-gress** [comment]
@mpenick , That looks like it should work for us. Do you also need a change to starctl to add an option for passing the new system property, "stargate.basedir" to the JVM on startup?

**Comment by mpenick** [comment]
> Or maybe I just need to set JAVA_OPTS="-Dstargate.basedir=/my/custom/path" prior to calling starctl?

:+1:

**Comment by john-gress** [comment]
We've been testing this, and it looks good. When can we expect it to go into a tagged release? Thanks.

**Comment by dougwettlaufer** [comment]
@john-gress we should be tagging v1.0.28 tomorrow (6/17).

**Comment by john-gress** [comment]
@dougwettlaufer , looks like the v1.0.28 release has been delayed. At least, I'm not seeing it. Can I get an update? Thanks.

**Comment by dougwettlaufer** [comment]
Hi @john-gress , very sorry about the delay. v1.0.28 was tagged yesterday.

**Comment by john-gress** [comment]
This fix is working well for us. Thanks.
